import type { IconSvgElement } from "@hugeicons/react";
import {
  AbacusIcon,
  AccessIcon,
  AddressBookIcon,
  AddTeamIcon,
  AiBrowserIcon,
  AiContentGenerator01Icon,
  AlAqsaMosqueIcon,
  AlarmClockIcon,
  AlarmSmokeIcon,
  AlbumIcon,
  AlgorithmIcon,
  AllBookmarkIcon,
  AlphabetArabicIcon,
  AlphabetBanglaIcon,
  AlphabetChineseIcon,
  AlphabetGreekIcon,
  AlphabetHebrewIcon,
  AlphabetHindiIcon,
  AlphabetJapaneseIcon,
  AlphabetKoreanIcon,
  AlphabetThaiIcon,
  AmbulanceIcon,
  AmericanFootballIcon,
  AnalyticsDownIcon,
  AnalyticsIcon,
  AnalyticsUpIcon,
  AnchorIcon,
  AnchorPointIcon,
  AntennaIcon,
  AnvilIcon,
  ApartmentIcon,
  ApertureIcon,
  ApiGatewayIcon,
  ApiIcon,
  AppointmentIcon,
  AppStoreIcon,
  AppWindowMacIcon,
  ArcBrowserIcon,
  ArrowDown02Icon,
  ArrowDownDoubleIcon,
  ArrowMoveDownLeftIcon,
  ArrowMoveDownRightIcon,
  ArrowReloadHorizontalIcon,
  ArrowRight02Icon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  ArrowUp01Icon,
  ArrowUp02Icon,
  ArrowUpDoubleIcon,
  ArrowUpDownIcon,
  ArrowUpRight01Icon,
  ArtboardIcon,
  ArtboardToolIcon,
  AsteroidIcon,
  AstronautIcon,
  AtomIcon,
  AtomicPowerIcon,
  AtSignIcon,
  AttachmentCircleIcon,
  AttachmentIcon,
  AttachmentSquareIcon,
  AudioBookIcon,
  AudioLinesIcon,
  AudioWaveformIcon,
  AudioWaveIcon,
  AvalancheIcon,
  AvocadoIcon,
  AwardIcon,
  AxeIcon,
  BabyBedIcon,
  BabyBottleIcon,
  BabyIcon,
  BackpackIcon,
  BacteriaIcon,
  BalanceScaleIcon,
  BalloonIcon,
  BananaIcon,
  BandageIcon,
  BankIcon,
  BarChartIcon,
  BarCodeIcon,
  BarcodeIcon,
  BarcodeScanIcon,
  BaseballBatIcon,
  BaseballHelmetIcon,
  BaseballIcon,
  BashIcon,
  BasketballHoopIcon,
  BasketballIcon,
  BatteryChargingIcon,
  BatteryEmptyIcon,
  BatteryFullIcon,
  BatteryIcon,
  BatteryLowIcon,
  BeachIcon,
  BeerIcon,
  BellDotIcon,
  BellIcon,
  BellRingIcon,
  BendToolIcon,
  BerlinTowerIcon,
  BicycleIcon,
  BikeIcon,
  BinaryCodeIcon,
  BinaryIcon,
  BioEnergyIcon,
  BirdIcon,
  BlockchainIcon,
  BlockGameIcon,
  BloodBagIcon,
  BloodBottleIcon,
  BloodIcon,
  BloodPressureIcon,
  BloodTypeIcon,
  BluetoothConnectedIcon,
  BluetoothIcon,
  BlurIcon,
  BlushBrushIcon,
  BoardMathIcon,
  BoatIcon,
  BodyPartLegIcon,
  BodyPartMuscleIcon,
  BoltIcon,
  Book02Icon,
  BookAIcon,
  BookBookmarkIcon,
  BookDashedIcon,
  BookDownIcon,
  BookEditIcon,
  BookHeartIcon,
  BookIcon,
  BookImageIcon,
  BookKeyIcon,
  BookLockIcon,
  BookMarkedIcon,
  BookmarkIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BookshelfIcon,
  BooksIcon,
  BookTextIcon,
  BookTypeIcon,
  BookUpTwoIcon,
  BookUserIcon,
  BoomBoxIcon,
  BoundingBoxIcon,
  BowlingBallIcon,
  BowlingIcon,
  BowlingPinsIcon,
  BoxIcon,
  BoxingBagIcon,
  BracketsIcon,
  BrainCircuitIcon,
  BrainCogIcon,
  BrainIcon,
  BreadIcon,
  BridgeIcon,
  BriefcaseIcon,
  BrowserIcon,
  BrushCleaningIcon,
  BrushIcon,
  BubbleChatFavouriteIcon,
  BubbleTeaIcon,
  BucketIcon,
  BuildingIcon,
  BulbChargingIcon,
  BulbIcon,
  BusFrontIcon,
  BusIcon,
  CableCarIcon,
  CableIcon,
  CactusIcon,
  CafeIcon,
  CakeIcon,
  CakeSliceIcon,
  CalculatorIcon,
  Calendar03Icon,
  CalendarAnalysisIcon,
  CalendarBlockIcon,
  CalendarCheckOut02Icon,
  CalendarClockIcon,
  CalendarCogIcon,
  CalendarDateOneIcon,
  CalendarDaysIcon,
  CalendarFavoriteIcon,
  CalendarFoldIcon,
  CalendarHeartIcon,
  CalendarLockIcon,
  CalendarLoveIcon,
  CalendarRangeIcon,
  CalendarSettingIcon,
  CalendarSyncIcon,
  CalendarUserIcon,
  CallDoneIcon,
  CallEndIcon,
  CallIcon,
  CallLockedIcon,
  CallMissedIcon,
  CallPausedIcon,
  CallRingingIcon,
  CallSparkIcon,
  CameraAiIcon,
  CameraAutomaticallyIcon,
  CameraIcon,
  CameraLensIcon,
  CameraMicrophoneIcon,
  CameraNightModeIcon,
  CameraRotatedIcon,
  CameraSmileIcon,
  CameraTripodIcon,
  CameraVideoIcon,
  CandyCaneIcon,
  CandyIcon,
  CanvasIcon,
  CardSimIcon,
  CarFrontIcon,
  CargoShipIcon,
  CarIcon,
  CarParkingIcon,
  CarrotIcon,
  CarSignalIcon,
  CarTimeIcon,
  CashierIcon,
  CassetteTapeIcon,
  CastleIcon,
  CatIcon,
  CctvCameraIcon,
  CctvIcon,
  CertificateIcon,
  ChartAnalysisIcon,
  ChartAreaIcon,
  ChartAverageIcon,
  ChartBarBigIcon,
  ChartBarLineIcon,
  ChartBubbleIcon,
  ChartCandleIcon,
  ChartColumnIcon,
  ChartDecreaseIcon,
  ChartDownIcon,
  ChartGanttIcon,
  ChartHighLowIcon,
  ChartIcon,
  ChartLineIcon,
  ChartMaximumIcon,
  ChartMediumIcon,
  ChartMinimumIcon,
  ChartNetworkIcon,
  ChartRadarIcon,
  ChartRingIcon,
  ChartRoseIcon,
  ChartScatterIcon,
  ChartSplineIcon,
  ChartUpIcon,
  ChatBotIcon,
  ChatDelayIcon,
  ChatDoneIcon,
  ChatEditIcon,
  ChatIcon,
  ChatIncomeIcon,
  ChatLockIcon,
  ChatOutcomeIcon,
  ChatPreviewIcon,
  ChatSparkIcon,
  ChatUserIcon,
  CheeseCakeIcon,
  CheeseIcon,
  ChefHatIcon,
  ChefIcon,
  ChemistryIcon,
  CherryIcon,
  ChessBishopIcon,
  ChessIcon,
  ChessKingIcon,
  ChessKnightIcon,
  ChessPawnIcon,
  ChessQueenIcon,
  ChessRookIcon,
  ChildIcon,
  ChinaTempleIcon,
  ChipIcon,
  ChurchIcon,
  CircleArrowShrink01Icon,
  CircleGaugeIcon,
  CirclePowerIcon,
  CircuitBoardIcon,
  CityIcon,
  ClapperboardIcon,
  ClappingIcon,
  CleanIcon,
  CleaningBucketIcon,
  ClipboardClockIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClipboardPasteIcon,
  ClipboardPenLineIcon,
  Clock01Icon,
  ClockFadingIcon,
  CloudBackupIcon,
  CloudBigRainIcon,
  CloudCogIcon,
  CloudDrizzleIcon,
  CloudFogIcon,
  CloudHailIcon,
  CloudIcon,
  CloudLightningIcon,
  CloudMidRainIcon,
  CloudMidSnowIcon,
  CloudOffIcon,
  CloudRainIcon,
  CloudServerIcon,
  CloudSnowIcon,
  CloudSunRainIcon,
  CloudSyncIcon,
  CloverIcon,
  CodeCircleIcon,
  CodeFolderIcon,
  CodeSimpleIcon,
  CodeSquareIcon,
  CodeXmlIcon,
  Coffee02Icon,
  CogIcon,
  CollapseIcon,
  CollectionsBookmarkIcon,
  ColorPickerIcon,
  ColumnsThreeCogIcon,
  CometIcon,
  CommandIcon,
  CommandLineIcon,
  CommentIcon,
  CompassIcon,
  ComputerEthernetIcon,
  ComputerTerminalIcon,
  ComputerVideoCallIcon,
  ComputerVideoIcon,
  ConsoleIcon,
  ContactBookIcon,
  ContactIcon,
  ContactRoundIcon,
  ContractsIcon,
  ContrastIcon,
  CookBookIcon,
  CookieIcon,
  CookingPotIcon,
  CornIcon,
  CottageIcon,
  CouponIcon,
  CouponPercentIcon,
  CourseIcon,
  CourtLawIcon,
  CProgrammingIcon,
  CpuChargeIcon,
  CpuIcon,
  CraneIcon,
  CraneTowerIcon,
  CropIcon,
  CrownIcon,
  CupSodaIcon,
  CursorMagicSelectionIcon,
  CursorProgressIcon,
  DashboardCircleIcon,
  DashedLine02Icon,
  DatabaseIcon,
  DataRecoveryIcon,
  DateTimeIcon,
  DeliveryBoxIcon,
  DeliveryDelayIcon,
  DeliveryReturnIcon,
  DeliverySecureIcon,
  DeliverySentIcon,
  DeliveryTrackingIcon,
  DeliveryTruckIcon,
  DeliveryViewIcon,
  DentalBracesIcon,
  DentalCareIcon,
  DentalToothIcon,
  DesertIcon,
  DeskIcon,
  DessertIcon,
  DeveloperIcon,
  DiamondIcon,
  DiamondPercentIcon,
  DiceFacesIcon,
  DiceIcon,
  DigitalClockIcon,
  DiningTableIcon,
  DiplomaIcon,
  DiscAlbumIcon,
  DiscIcon,
  DiscordIcon,
  DiscountIcon,
  DiscountTagIcon,
  DiscThreeIcon,
  DiscTwoIcon,
  DnaIcon,
  DoctorIcon,
  DocumentAttachmentIcon,
  DocumentCodeIcon,
  DocumentValidationIcon,
  DominoIcon,
  DonutIcon,
  DoorLockIcon,
  DraftingCompassIcon,
  DragDropHorizontalIcon,
  DragDropVerticalIcon,
  DrawingModeIcon,
  DrillIcon,
  DrinkIcon,
  DriveIcon,
  DroneIcon,
  DropletIcon,
  DrumIcon,
  DumbbellIcon,
  DumpTruckIcon,
  EarthIcon,
  EarthLockIcon,
  EclipseIcon,
  EcoEnergyIcon,
  EcoLabIcon,
  EcoPowerIcon,
  Edit04Icon,
  EggFriedIcon,
  EggIcon,
  EiffelTowerIcon,
  ElectricHomeIcon,
  ElectricPlugsIcon,
  ElectricWireIcon,
  EncryptIcon,
  EnergyIcon,
  EngineIcon,
  EquipmentGymIcon,
  EraserIcon,
  ExcavatorIcon,
  ExpandIcon,
  EyeClosedIcon,
  FaceIdIcon,
  FaceMimicIcon,
  FactoryIcon,
  FallingStarIcon,
  FanIcon,
  FastWindIcon,
  FavouriteCircleIcon,
  FavouriteIcon,
  FavouriteSquareIcon,
  FeatherIcon,
  FerryBoatIcon,
  File01Icon,
  FileAddIcon,
  FileArchiveIcon,
  FileAttachmentIcon,
  FileAudioIcon,
  FileBlockIcon,
  FileBookmarkIcon,
  FileBoxIcon,
  FileBracesIcon,
  FileChartPieIcon,
  FileCheckIcon,
  FileClockIcon,
  FileCloudIcon,
  FileCodeCornerIcon,
  FileCodeIcon,
  FileCogIcon,
  FileDigitIcon,
  FileEditIcon,
  FileEmpty02Icon,
  FileEmptyIcon,
  FileFavouriteIcon,
  FileHeartIcon,
  FileImageIcon,
  FileInputIcon,
  FileKeyIcon,
  FileLockedIcon,
  FileLockIcon,
  FileMusicIcon,
  FileOutputIcon,
  FilePasteIcon,
  FilePenIcon,
  FilePenLineIcon,
  FilePinIcon,
  FilePlayIcon,
  FileQuestionMarkIcon,
  FileScanIcon,
  FileScriptIcon,
  FileSearchIcon,
  FileStackIcon,
  FileStarIcon,
  FileSyncIcon,
  FileTerminalIcon,
  FileTypeIcon,
  FileUserIcon,
  FileVideoIcon,
  FileXCornerIcon,
  FileZipIcon,
  FilmIcon,
  FilmRollIcon,
  FireIcon,
  FirePitIcon,
  FirewallIcon,
  FireworksIcon,
  FirstAidKitIcon,
  FishFoodIcon,
  FishIcon,
  FishingHookIcon,
  FlagIcon,
  FlagTriangleLeftIcon,
  FlagTriangleRightIcon,
  FlameIcon,
  FlashlightIcon,
  FlaskConicalIcon,
  FlaskRoundIcon,
  FlipPhoneIcon,
  FloppyDiskIcon,
  FlowchartIcon,
  FlowerIcon,
  FocusIcon,
  FocusPointIcon,
  Folder02Icon,
  FolderAudioIcon,
  FolderBlockIcon,
  FolderClockIcon,
  FolderCloudIcon,
  FolderCodeIcon,
  FolderCogIcon,
  FolderDotIcon,
  FolderEditIcon,
  FolderHeartIcon,
  FolderInputIcon,
  FolderKeyIcon,
  FolderLockIcon,
  FolderMusicIcon,
  FolderOutputIcon,
  FolderPenIcon,
  FolderPinIcon,
  FolderRemoveIcon,
  FolderRootIcon,
  FolderSyncIcon,
  FolderTreeIcon,
  FolderVideoIcon,
  FolderZipIcon,
  FootballIcon,
  FootballPitchIcon,
  ForkliftIcon,
  FormIcon,
  FrameIcon,
  FuelIcon,
  FuelStationIcon,
  FullSignalIcon,
  FunctionIcon,
  FunctionSquareIcon,
  FunnelIcon,
  GalaxyIcon,
  GalleryHorizontalIcon,
  GalleryThumbnailsIcon,
  GalleryVerticalEndIcon,
  GalleryVerticalIcon,
  GameControllerIcon,
  GameIcon,
  GamepadDirectionalIcon,
  GamepadIcon,
  GasPipeIcon,
  GaugeIcon,
  GavelIcon,
  GearsIcon,
  GemIcon,
  GiftCardIcon,
  GiftIcon,
  GitBranchIcon,
  GitForkIcon,
  GithubIcon,
  GitMergeIcon,
  GitPullRequestArrow,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  GiveBloodIcon,
  GivePillIcon,
  GlassesIcon,
  GlassWaterIcon,
  GlobalEducationIcon,
  GlobeLockIcon,
  GoalIcon,
  GolfBallIcon,
  GolfBatIcon,
  GolfCartIcon,
  GolfHoleIcon,
  GpsSignalIcon,
  GraduateFemaleIcon,
  GraduateMaleIcon,
  GraduationCapIcon,
  GraduationScrollIcon,
  GrapeIcon,
  GravityIcon,
  GridTableIcon,
  GridViewIcon,
  GroupIcon,
  GroupItemsIcon,
  GuitarIcon,
  HalalLabIcon,
  HammerIcon,
  HandBagIcon,
  HandHeartIcon,
  HandHelpingIcon,
  HandshakeIcon,
  HangingClockIcon,
  HardDriveIcon,
  HashtagIcon,
  HatGlassesIcon,
  HeadphonesIcon,
  HeadsetConnectedIcon,
  HeadsetIcon,
  HealthIcon,
  HeartCrackIcon,
  HeartHandshakeIcon,
  HeartIcon,
  HeartPulseIcon,
  HelicopterIcon,
  HighlighterIcon,
  HistoryIcon,
  HoldPhoneIcon,
  HomeIcon,
  HomeWifiIcon,
  HoneyIcon,
  HonorIcon,
  HonourStarIcon,
  HorseIcon,
  HospitalBedIcon,
  HospitalIcon,
  HospitalLocationIcon,
  HotAirBalloonIcon,
  HotelBellIcon,
  HotelIcon,
  HotPriceIcon,
  HourglassIcon,
  HouseHeartIcon,
  HouseIcon,
  HousePlugIcon,
  HtmlFileIcon,
  HydroPowerIcon,
  IceCreamBowlIcon,
  IceCreamIcon,
  IdeaIcon,
  IdIcon,
  ImageActualSizeIcon,
  ImageCompositionIcon,
  ImageCropIcon,
  ImageDeleteIcon,
  ImageDoneIcon,
  ImageDownIcon,
  ImageFlipVerticalIcon,
  ImageIcon,
  ImagePlayIcon,
  ImageToVideoIcon,
  ImageUpIcon,
  ImageUpscaleIcon,
  InboxIcon,
  InboxUnreadIcon,
  IncognitoIcon,
  InfinityIcon,
  InjectionIcon,
  InputCursorTextIcon,
  InputLongTextIcon,
  InputNumericIcon,
  InputShortTextIcon,
  InputTextIcon,
  InsertBottomImageIcon,
  InsertPiIcon,
  InsertTopImageIcon,
  InspectCodeIcon,
  InternetIcon,
  InvoiceIcon,
  IslandIcon,
  JavaScriptIcon,
  JoystickIcon,
  JudgeIcon,
  JusticeScaleIcon,
  KeyboardIcon,
  KeyIcon,
  KeyRoundIcon,
  KeySquareIcon,
  KiteIcon,
  KnifeBreadIcon,
  KnifeIcon,
  LabelIcon,
  LakeIcon,
  LampCeilingIcon,
  LampDeskIcon,
  LampFloorIcon,
  LampIcon,
  LampWallDownIcon,
  LampWallUpIcon,
  LandmarkIcon,
  LanguageCircleIcon,
  LanguageSkillIcon,
  LanguageSquareIcon,
  LanternIcon,
  LaptopCloudIcon,
  LaptopIcon,
  LaptopVideoIcon,
  LassoIcon,
  LassoSelectIcon,
  LassoToolIcon,
  LaurelWreathFirstIcon,
  LaurelWreathIcon,
  LaurelWreathLeftIcon,
  LaurelWreathRightIcon,
  LayerIcon,
  Layers01Icon,
  LayersLogoIcon,
  LayoutTableIcon,
  LayoutTwoColumnIcon,
  LayoutTwoRowIcon,
  LeafIcon,
  LeafyGreenIcon,
  LeetcodeIcon,
  LeftToRightListStarIcon,
  LegalDocumentIcon,
  LegalHammerIcon,
  LegalIcon,
  LensConcaveIcon,
  LensConvexIcon,
  LibraryBigIcon,
  LibraryIcon,
  LicenseIcon,
  LicenseNoIcon,
  LicensePinIcon,
  LicenseThirdPartyIcon,
  LiftTruckIcon,
  LightbulbIcon,
  LighthouseIcon,
  LimitationIcon,
  LinkSquare02Icon,
  ListViewIcon,
  LocationIcon,
  LockedIcon,
  LockIcon,
  LockKeyIcon,
  LockOpenIcon,
  LockSyncIcon,
  LuggageIcon,
  MachineRobotIcon,
  MagicWandIcon,
  MagnetIcon,
  Mail02Icon,
  MailAccountIcon,
  MailAtSignIcon,
  MailBlockIcon,
  MailboxIcon,
  MailEditIcon,
  MailLockIcon,
  MailLoveIcon,
  MailOpen01Icon,
  MailReplyIcon,
  MailSendIcon,
  MailVoiceIcon,
  ManagerIcon,
  ManIcon,
  ManWomanIcon,
  MapIcon,
  MapPinHouseIcon,
  MapPinIcon,
  MapPinnedIcon,
  MapPinPenIcon,
  MapPinXInsideIcon,
  MarketAnalysisIcon,
  MarketOrderIcon,
  MaskTheaterIcon,
  MasterCardIcon,
  MathIcon,
  McpServerIcon,
  MedalFirstPlaceIcon,
  MedalIcon,
  MedalSecondPlaceIcon,
  MedalThirdPlaceIcon,
  MedicalFileIcon,
  MedicalMaskIcon,
  MedicineBottleIcon,
  MedicineIcon,
  MedicineSyrupIcon,
  MeetingRoomIcon,
  MegaphoneIcon,
  MemoryStickIcon,
  MentorIcon,
  Menu02Icon,
  MessageAdd02Icon,
  MessageCircleIcon,
  MessageDoneIcon,
  MessageEditIcon,
  MessageIcon,
  MessageLockIcon,
  MessageTranslateIcon,
  MetroIcon,
  Mic02Icon,
  MicrochipIcon,
  MicroscopeIcon,
  MicVocalIcon,
  MilestoneIcon,
  MilkBottleIcon,
  MilkCartonIcon,
  MilkIcon,
  MilkOatIcon,
  MoleculesIcon,
  MonitorCloudIcon,
  MonitorIcon,
  MonitorSpeakerIcon,
  MoonCloudIcon,
  MoonFastWindIcon,
  MoonIcon,
  MoonSlowWindIcon,
  MoonStarIcon,
  MosqueIcon,
  MosqueLocationIcon,
  MountainIcon,
  MountainSnowIcon,
  MouseIcon,
  MushroomIcon,
  MusicIcon,
  MusicNoteIcon,
  MusicNoteSquareIcon,
  MusicThreeIcon,
  NecklaceIcon,
  NetworkIcon,
  NeuralNetworkIcon,
  NewOfficeIcon,
  NoMeetingRoomIcon,
  NonBinaryIcon,
  NotebookIcon,
  NotebookTabsIcon,
  NotebookTextIcon,
  NoteDoneIcon,
  NoteEditIcon,
  NoteIcon,
  NotepadTextIcon,
  NotificationIcon,
  NuclearPowerIcon,
  NutIcon,
  OctopusIcon,
  OfficeChairIcon,
  OfficeIcon,
  OlympicTorchIcon,
  OnlineLearningIcon,
  OpenSourceIcon,
  OrangeIcon,
  PackageDeliveredIcon,
  PackageIcon,
  PackageMovingIcon,
  PackageOpenIcon,
  PackageProcessIcon,
  PackageReceiveIcon,
  PackageSentIcon,
  PaintBoardIcon,
  PaintBrushIcon,
  PaintBucketIcon,
  PaintRollerIcon,
  PandaIcon,
  PartyIcon,
  PartyPopperIcon,
  PassportExpiredIcon,
  PassportIcon,
  PassportValidIcon,
  PathIcon,
  PauseIcon,
  PawPrintIcon,
  PencilIcon,
  PencilLineIcon,
  PencilRulerIcon,
  PenConnectUsbIcon,
  PenIcon,
  PenLineIcon,
  PenToolIcon,
  PercentIcon,
  PersonStandingIcon,
  PetrolPumpIcon,
  PhoneCallIcon,
  PhoneIcon,
  PhoneLockIcon,
  PhoneShakeIcon,
  PhysicsIcon,
  PickaxeIcon,
  PictureInPictureIcon,
  PictureInPictureOnIcon,
  PieChartIcon,
  PieIcon,
  PiIcon,
  PillBottleIcon,
  PillIcon,
  PillsTabletIcon,
  PinCodeIcon,
  PineTreeIcon,
  PinIcon,
  PinLocationIcon,
  PinOffIcon,
  PisaTowerIcon,
  PizzaIcon,
  PlaneIcon,
  PlantIcon,
  PlateIcon,
  PlayIcon,
  PlaylistIcon,
  PlayStoreIcon,
  PlazaIcon,
  PlugIcon,
  PlugSocketIcon,
  PlugZapIcon,
  PlusMinusSquare01Icon,
  PlusSignIcon,
  PocketKnifeIcon,
  PodcastIcon,
  PoliceCapIcon,
  PoliceCarIcon,
  PoliceStationIcon,
  PoolTableIcon,
  PowerIcon,
  PowerServiceIcon,
  PowerSocketIcon,
  PresentationIcon,
  PrinterIcon,
  PrinterThreeDIcon,
  PrismIcon,
  ProfileIcon,
  ProgressIcon,
  PulseIcon,
  PurseIcon,
  PuzzleIcon,
  QrCodeIcon,
  QrCodeScanIcon,
  RabbitIcon,
  RacingFlagIcon,
  RadarIcon,
  RadiationIcon,
  RadioIcon,
  RadioReceiverIcon,
  RadioTowerIcon,
  RainbowIcon,
  RainDropIcon,
  RainIcon,
  RamMemoryIcon,
  RankingIcon,
  ReceiptIcon,
  ReceiptTextIcon,
  RecycleIcon,
  Refresh01Icon,
  ReminderIcon,
  RemovePiIcon,
  RepeatIcon,
  RestaurantIcon,
  RibbonIcon,
  RiceBowlIcon,
  RoadIcon,
  RoadWaysideIcon,
  RoboticIcon,
  RobotIcon,
  RocketIcon,
  RollingPinIcon,
  RoseIcon,
  RouterIcon,
  RssIcon,
  RssLockedIcon,
  RulerIcon,
  SafeBoxIcon,
  SafeDeliveryIcon,
  SafeIcon,
  SafetyPinIcon,
  SailboatIcon,
  SalahTimeIcon,
  SaleTagIcon,
  SatelliteDishIcon,
  SatelliteIcon,
  SaveEnergyIcon,
  ScaleIcon,
  ScaleThreeDIcon,
  ScanEyeIcon,
  ScanFaceIcon,
  ScanHeartIcon,
  ScanImageIcon,
  ScanTextIcon,
  SchoolBellIcon,
  SchoolBusIcon,
  SchoolIcon,
  SchoolReportCardIcon,
  SchoolTieIcon,
  ScissorsIcon,
  ScooterIcon,
  SdCardIcon,
  SecurityCheckIcon,
  SecurityIcon,
  SemiTruckIcon,
  SentIcon,
  ServerCogIcon,
  ServerIcon,
  ShellIcon,
  ShieldBanIcon,
  ShieldCogIcon,
  ShieldIcon,
  ShieldKeyIcon,
  ShieldUserIcon,
  ShipIcon,
  ShipWheelIcon,
  ShoppingBagFavoriteIcon,
  ShoppingBagIcon,
  ShoppingBasketFavoriteIcon,
  ShoppingBasketIcon,
  ShoppingCartFavoriteIcon,
  ShoppingCartIcon,
  ShopSignIcon,
  ShovelIcon,
  SidebarBottomIcon,
  SidebarRightIcon,
  SigmaIcon,
  SignalIcon,
  SignalNoIcon,
  SignLanguageCIcon,
  SirenIcon,
  SketchIcon,
  SkiIcon,
  SmartPhone01Icon,
  SmartPhoneIcon,
  SmartWatchIcon,
  SmileIcon,
  SmsCodeIcon,
  SnailIcon,
  SnowIcon,
  SoftDrinkIcon,
  SoftwareIcon,
  SolarEnergyIcon,
  SolarPowerIcon,
  SolarSystemIcon,
  Sorting01Icon,
  SourceCodeCircleIcon,
  SourceCodeSquareIcon,
  SparkleIcon,
  SpeakerIcon,
  SpeechIcon,
  SpeedTrainIcon,
  SplineIcon,
  SpoonAndKnifeIcon,
  SpoonIcon,
  SproutIcon,
  SquareIcon,
  SquarePowerIcon,
  SquareTerminalIcon,
  SquareUnlock02Icon,
  SquirrelIcon,
  StackStarIcon,
  StampIcon,
  StarAwardIcon,
  StarCircleIcon,
  StarFaceIcon,
  StarHalfIcon,
  StarIcon,
  StarSquareIcon,
  StethoscopeIcon,
  StickerIcon,
  StickyNoteIcon,
  StopWatchIcon,
  StoreIcon,
  StoreLocationIcon,
  StoreManagementIcon,
  StreetFoodIcon,
  StudentCardIcon,
  StudentIcon,
  StudyDeskIcon,
  StudyLampIcon,
  SubmarineIcon,
  SunCloudIcon,
  SunDimIcon,
  SunIcon,
  SunMoonIcon,
  SunriseIcon,
  SunsetIcon,
  SunSnowIcon,
  SushiIcon,
  SwatchBookIcon,
  SwimmingCapIcon,
  SwimmingIcon,
  SwitchCameraIcon,
  SyringeIcon,
  SystemUpdateIcon,
  TableIcon,
  TableLampIcon,
  TableRoundIcon,
  TableTennisBatIcon,
  TabletPenIcon,
  TagIcon,
  TankerTruckIcon,
  TapeMeasureIcon,
  TaxiIcon,
  TeacherIcon,
  TeaIcon,
  TeamWorkIcon,
  TeaPodIcon,
  TelescopeIcon,
  TemperatureIcon,
  TennisBallIcon,
  TennisRacketIcon,
  TentIcon,
  TentTreeIcon,
  TestTube01Icon,
  TestTubeDiagonalIcon,
  TestTubeIcon,
  TextAllCapsIcon,
  TextBoldIcon,
  TextCircleIcon,
  TextClearIcon,
  TextColorIcon,
  TextFontIcon,
  TextIcon,
  TextItalicIcon,
  TextQuoteIcon,
  TextSelectIcon,
  TextToImageIcon,
  TextWrapIcon,
  TheaterIcon,
  ThermometerIcon,
  ThumbsUpDownIcon,
  ThumbsUpEllipseIcon,
  ThumbsUpIcon,
  ThumbsUpRectangleIcon,
  TimeHalfPassIcon,
  TimeIcon,
  TimelineEventIcon,
  TimelineIcon,
  TimelineListIcon,
  TimeManagementIcon,
  TimeQuarterIcon,
  TimeQuarterPassIcon,
  TimerIcon,
  TimerResetIcon,
  TimeScheduleIcon,
  TimeSettingIcon,
  TimeZoneIcon,
  TornadoIcon,
  TowTruckIcon,
  ToyBrickIcon,
  ToyTrainIcon,
  TractorIcon,
  TradeDownIcon,
  TradeMarkIcon,
  TradeUpIcon,
  TrafficConeIcon,
  TrafficJamIcon,
  TrafficLightIcon,
  TrainFrontIcon,
  TrainIcon,
  TrainTrackIcon,
  TramFrontIcon,
  TramIcon,
  TranslateIcon,
  TravelBagIcon,
  TreeIcon,
  TreePalmIcon,
  TrolleyIcon,
  TrophyIcon,
  TruckDeliveryIcon,
  TruckIcon,
  TruckReturnIcon,
  TurntableIcon,
  TurtleIcon,
  TwinTowerIcon,
  TypeIcon,
  UmbrellaIcon,
  Unarchive03Icon,
  UniversityIcon,
  UsbBugsIcon,
  UsbIcon,
  UsbMemoryIcon,
  UserAccountIcon,
  UserAddIcon,
  UserAiIcon,
  UserBlockIcon,
  UserCheckIcon,
  UserCircleIcon,
  UserCogIcon,
  UserEditIcon,
  UserFullViewIcon,
  UserGroupIcon,
  UserIcon,
  UserKeyIcon,
  UserListIcon,
  UserLockIcon,
  UserLoveIcon,
  UserMultipleIcon,
  UserPenIcon,
  UserQuestionIcon,
  UserRoadsideIcon,
  UserRoundCogIcon,
  UserRoundKeyIcon,
  UserSharingIcon,
  UsersIcon,
  UserSquareIcon,
  UserStarIcon,
  UserStoryIcon,
  UserTimeIcon,
  UtensilsIcon,
  VaccineIcon,
  VanIcon,
  VaultIcon,
  VideoAiIcon,
  VideoCameraAiIcon,
  VideoConsoleIcon,
  VideoIcon,
  VideoReplayIcon,
  ViewAgendaIcon,
  ViewIcon,
  ViewOffIcon,
  VillaIcon,
  VintageClockIcon,
  VoiceCommentIcon,
  VoiceIcon,
  VoiceIdIcon,
  VoicemailIcon,
  VolleyballIcon,
  VolumeHighIcon,
  VolumeIcon,
  VolumeLowIcon,
  VolumeUpIcon,
  VoucherIcon,
  VrGlassesIcon,
  WalletCardsIcon,
  WalletDoneIcon,
  WalletIcon,
  WallLampIcon,
  WandIcon,
  WatchIcon,
  WaterEnergyIcon,
  WatermelonIcon,
  WaterPumpIcon,
  WaveIcon,
  WavesLadderIcon,
  WebDesignIcon,
  WeddingIcon,
  WeightScaleIcon,
  WellnessIcon,
  WheelchairIcon,
  WhiteboardIcon,
  WifiCogIcon,
  WifiHighIcon,
  WifiIcon,
  WifiLockIcon,
  WifiLowIcon,
  WifiPenIcon,
  WifiSyncIcon,
  WifiZeroIcon,
  WindIcon,
  WindPowerIcon,
  WindSurfIcon,
  WindTurbineIcon,
  WomanIcon,
  WorkHistoryIcon,
  WorkoutRunIcon,
  WrenchIcon,
  YogaBallIcon,
  YogaIcon,
  YogaMatIcon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
} from "@hugeicons/core-free-icons";
import { type ExtendedIconMap, registerExtendedIcons } from "./icon-registry";

const PaletteStrokeRoundedIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M21.8205 10.4127C22.062 11.8519 22.1827 12.5715 21.2423 13.9326C21.1459 14.0722 20.8966 14.3713 20.777 14.4911C19.6103 15.6586 18.4308 15.6586 16.0716 15.6586H14.1392C13.5085 15.6586 13.1931 15.6586 12.9639 15.7142C11.9586 15.9581 11.3031 16.9391 11.453 17.9755C11.4872 18.2118 11.6043 18.5085 11.8386 19.102C11.9345 19.3449 11.9824 19.4664 12.0136 19.7304C12.1292 20.7084 11.0869 21.9508 10.1158 21.9926C9.85358 22.0039 9.83681 22.0002 9.80326 21.9926C7.66174 21.51 5.66204 20.3123 4.18389 18.4421C0.736789 14.0808 1.43146 7.71364 5.73548 4.22064C10.0395 0.727643 16.323 1.43156 19.7701 5.79289C20.868 7.1819 21.5457 8.77438 21.8205 10.4127Z",
      fill: "none",
      fillRule: "evenodd",
      clipRule: "evenodd",
      stroke: "currentColor",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M7.36719 7.74976H7.24219M7.49219 7.74976C7.49219 7.88783 7.38026 7.99976 7.24219 7.99976C7.10412 7.99976 6.99219 7.88783 6.99219 7.74976C6.99219 7.61169 7.10412 7.49976 7.24219 7.49976C7.38026 7.49976 7.49219 7.61169 7.49219 7.74976Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M7.36719 15.7498H7.24219M7.49219 15.7498C7.49219 15.8878 7.38026 15.9998 7.24219 15.9998C7.10412 15.9998 6.99219 15.8878 6.99219 15.7498C6.99219 15.6117 7.10412 15.4998 7.24219 15.4998C7.38026 15.4998 7.49219 15.6117 7.49219 15.7498Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M11.8672 5.74976H11.7422M11.9922 5.74976C11.9922 5.88783 11.8803 5.99976 11.7422 5.99976C11.6041 5.99976 11.4922 5.88783 11.4922 5.74976C11.4922 5.61169 11.6041 5.49976 11.7422 5.49976C11.8803 5.49976 11.9922 5.61169 11.9922 5.74976Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M16.3672 7.74976H16.2422M16.4922 7.74976C16.4922 7.88783 16.3803 7.99976 16.2422 7.99976C16.1041 7.99976 15.9922 7.88783 15.9922 7.74976C15.9922 7.61169 16.1041 7.49976 16.2422 7.49976C16.3803 7.49976 16.4922 7.61169 16.4922 7.74976Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M18.3672 11.7498H18.2422M18.4922 11.7498C18.4922 11.8878 18.3803 11.9998 18.2422 11.9998C18.1041 11.9998 17.9922 11.8878 17.9922 11.7498C17.9922 11.6117 18.1041 11.4998 18.2422 11.4998C18.3803 11.4998 18.4922 11.6117 18.4922 11.7498Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "5",
    },
  ],
  [
    "path",
    {
      d: "M5.86719 11.7498H5.74219M5.99219 11.7498C5.99219 11.8878 5.88026 11.9998 5.74219 11.9998C5.60412 11.9998 5.49219 11.8878 5.49219 11.7498C5.49219 11.6117 5.60412 11.4998 5.74219 11.4998C5.88026 11.4998 5.99219 11.6117 5.99219 11.7498Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "6",
    },
  ],
];

export const EXTENDED_ICON_MAP: ExtendedIconMap = {
  AiBrowser: AiBrowserIcon,
  AiContentGenerator01: AiContentGenerator01Icon,
  AlignLeft: Menu02Icon,
  AppWindow: BrowserIcon,
  ArchiveRestore: Unarchive03Icon,
  ArrowDown: ArrowDown02Icon,
  ArrowRight: ArrowRight02Icon,
  ArrowReloadHorizontal: ArrowReloadHorizontalIcon,
  ArrowUp: ArrowUp02Icon,
  ArrowUpDown: ArrowUpDownIcon,
  ArrowTurnBackward: ArrowTurnBackwardIcon,
  ArrowTurnForward: ArrowTurnForwardIcon,
  ArrowUpRight: ArrowUpRight01Icon,
  Beaker: TestTube01Icon,
  BellDot: BellDotIcon,
  Browser: BrowserIcon,
  Brain: BrainIcon,
  Calendar: Calendar03Icon,
  CalendarCheckOut02: CalendarCheckOut02Icon,
  ChartColumn: ChartColumnIcon,
  ChevronUp: ArrowUp01Icon,
  ChevronsDown: ArrowDownDoubleIcon,
  ChevronsUp: ArrowUpDoubleIcon,
  CircleArrowShrink: CircleArrowShrink01Icon,
  Clean: CleanIcon,
  Clock: Clock01Icon,
  Cloud: CloudIcon,
  CloudOff: CloudOffIcon,
  Coffee: Coffee02Icon,
  Columns2: LayoutTwoColumnIcon,
  CornerDownLeft: ArrowMoveDownLeftIcon,
  CornerDownRight: ArrowMoveDownRightIcon,
  Discord: DiscordIcon,
  DateTime: DateTimeIcon,
  Github: GithubIcon,
  DragDropHorizontal: DragDropHorizontalIcon,
  DragDropVertical: DragDropVerticalIcon,
  EditFile: Edit04Icon,
  ElectricPlugs: ElectricPlugsIcon,
  Eye: ViewIcon,
  EyeOff: ViewOffIcon,
  Explore: Book02Icon,
  ExternalLink: LinkSquare02Icon,
  FileDiff: PlusMinusSquare01Icon,
  File: FileEmpty02Icon,
  FileAttachment: FileAttachmentIcon,
  FileQuestion: FileQuestionMarkIcon,
  FileText: File01Icon,
  FolderOpen: Folder02Icon,
  FolderEdit: FolderEditIcon,
  FolderMinus: FolderRemoveIcon,
  Fork: GitForkIcon,
  GitBranch: GitBranchIcon,
  GitMerge: GitMergeIcon,
  GitPullRequest: GitPullRequestIcon,
  GitPullRequestArrow: GitPullRequestArrow,
  GitPullRequestClosed: GitPullRequestClosedIcon,
  GitPullRequestDraft: GitPullRequestDraftIcon,
  Globe: InternetIcon,
  GridView: GridViewIcon,
  Laptop: LaptopIcon,
  Layers: Layers01Icon,
  Limitation: LimitationIcon,
  ListView: ListViewIcon,
  Lock: LockIcon,
  Mail: Mail02Icon,
  MailOpen: MailOpen01Icon,
  Maximize2: ExpandIcon,
  Mic: Mic02Icon,
  Minimize2: CollapseIcon,
  NewTab: DashedLine02Icon,
  PackageReceive: PackageReceiveIcon,
  Palette: PaletteStrokeRoundedIcon,
  PanelBottom: SidebarBottomIcon,
  PanelRight: SidebarRightIcon,
  Paperclip: AttachmentIcon,
  Pause: PauseIcon,
  Pin: PinIcon,
  PinOff: PinOffIcon,
  Play: PlayIcon,
  Plus: PlusSignIcon,
  Puzzle: PuzzleIcon,
  Repeat: RepeatIcon,
  SecurityCheck: SecurityCheckIcon,
  RotateCcw: Refresh01Icon,
  Rows2: LayoutTwoRowIcon,
  Sent: SentIcon,
  SideChat: MessageAdd02Icon,
  Smartphone: SmartPhone01Icon,
  Sort: Sorting01Icon,
  Square: SquareIcon,
  SquareUnlock02: SquareUnlock02Icon,
  Star: StarIcon,
  TextWrap: TextWrapIcon,
  TimeSchedule: TimeScheduleIcon,
  UserRound: UserIcon,
  ZoomIn: ZoomInAreaIcon,
  ZoomOut: ZoomOutAreaIcon,

  CodeSimple: CodeSimpleIcon,
  CodeCircle: CodeCircleIcon,
  CodeSquare: CodeSquareIcon,
  CodeXml: CodeXmlIcon,
  CodeFolder: CodeFolderIcon,
  DocumentCode: DocumentCodeIcon,
  FileCode: FileCodeIcon,
  Command: CommandIcon,
  CommandLine: CommandLineIcon,
  Function: FunctionIcon,
  FunctionSquare: FunctionSquareIcon,
  Algorithm: AlgorithmIcon,
  Binary: BinaryIcon,
  BinaryCode: BinaryCodeIcon,
  Brackets: BracketsIcon,
  Api: ApiIcon,
  McpServer: McpServerIcon,
  Keyboard: KeyboardIcon,
  Mouse: MouseIcon,
  Monitor: MonitorIcon,
  Cpu: CpuIcon,
  Robot: RobotIcon,
  OpenSource: OpenSourceIcon,
  CircuitBoard: CircuitBoardIcon,
  CloudServer: CloudServerIcon,
  CloudCog: CloudCogIcon,
  CloudSync: CloudSyncIcon,
  CloudBackup: CloudBackupIcon,
  Database: DatabaseIcon,
  Server: ServerIcon,
  ServerCog: ServerCogIcon,
  Microchip: MicrochipIcon,
  Chip: ChipIcon,
  ComputerEthernet: ComputerEthernetIcon,
  BluetoothConnected: BluetoothConnectedIcon,
  Wifi: WifiIcon,
  Router: RouterIcon,
  Antenna: AntennaIcon,
  Satellite: SatelliteIcon,
  SatelliteDish: SatelliteDishIcon,
  Firewall: FirewallIcon,
  GlobeLock: GlobeLockIcon,
  Battery: BatteryIcon,
  BatteryCharging: BatteryChargingIcon,
  Power: PowerIcon,
  Blockchain: BlockchainIcon,
  FileQuestionMark: FileQuestionMarkIcon,
  FileAdd: FileAddIcon,
  FileCheck: FileCheckIcon,
  FileEdit: FileEditIcon,
  FileSearch: FileSearchIcon,
  FileArchive: FileArchiveIcon,
  FileBox: FileBoxIcon,
  FilePen: FilePenIcon,
  Clipboard: ClipboardIcon,
  ClipboardList: ClipboardListIcon,
  Notebook: NotebookIcon,
  Book: BookIcon,
  BookOpen: BookOpenIcon,
  BookText: BookTextIcon,
  Books: BooksIcon,
  Bookshelf: BookshelfIcon,
  Inbox: InboxIcon,
  Briefcase: BriefcaseIcon,
  AddressBook: AddressBookIcon,
  Analytics: AnalyticsIcon,
  AnalyticsUp: AnalyticsUpIcon,
  AnalyticsDown: AnalyticsDownIcon,
  BarChart: BarChartIcon,
  ChartLine: ChartLineIcon,
  ChartArea: ChartAreaIcon,
  ChartBarBig: ChartBarBigIcon,
  ChartScatter: ChartScatterIcon,
  ChartRadar: ChartRadarIcon,
  ChartSpline: ChartSplineIcon,
  PieChart: PieChartIcon,
  DashboardCircle: DashboardCircleIcon,
  Gauge: GaugeIcon,
  Percent: PercentIcon,
  Table: TableIcon,
  Brush: BrushIcon,
  PaintBrush: PaintBrushIcon,
  ColorPicker: ColorPickerIcon,
  Image: ImageIcon,
  Camera: CameraIcon,
  CameraVideo: CameraVideoIcon,
  Video: VideoIcon,
  Music: MusicIcon,
  AudioWaveform: AudioWaveformIcon,
  Headphones: HeadphonesIcon,
  Film: FilmIcon,
  Album: AlbumIcon,
  Disc: DiscIcon,
  Artboard: ArtboardIcon,
  PenTool: PenToolIcon,
  Pencil: PencilIcon,
  Ruler: RulerIcon,
  Crop: CropIcon,
  Contrast: ContrastIcon,
  Blur: BlurIcon,
  Canvas: CanvasIcon,
  Clapperboard: ClapperboardIcon,
  Atom: AtomIcon,
  FlaskConical: FlaskConicalIcon,
  Microscope: MicroscopeIcon,
  Telescope: TelescopeIcon,
  Dna: DnaIcon,
  Molecules: MoleculesIcon,
  Physics: PhysicsIcon,
  Calculator: CalculatorIcon,
  Gears: GearsIcon,
  Magnet: MagnetIcon,
  Radiation: RadiationIcon,
  Rocket: RocketIcon,
  Gravity: GravityIcon,
  Infinity: InfinityIcon,
  Engine: EngineIcon,
  Hammer: HammerIcon,
  Wrench: WrenchIcon,
  Asteroid: AsteroidIcon,
  NuclearPower: NuclearPowerIcon,
  Pickaxe: PickaxeIcon,
  Tree: TreeIcon,
  Leaf: LeafIcon,
  LeafyGreen: LeafyGreenIcon,
  Flower: FlowerIcon,
  Cactus: CactusIcon,
  PineTree: PineTreeIcon,
  Mountain: MountainIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Droplet: DropletIcon,
  Fire: FireIcon,
  Flame: FlameIcon,
  Earth: EarthIcon,
  Map: MapIcon,
  MapPin: MapPinIcon,
  Location: LocationIcon,
  Home: HomeIcon,
  House: HouseIcon,
  Building: BuildingIcon,
  City: CityIcon,
  Beach: BeachIcon,
  Island: IslandIcon,
  Fish: FishIcon,
  Bird: BirdIcon,
  Lighthouse: LighthouseIcon,
  Users: UsersIcon,
  UserGroup: UserGroupIcon,
  UserMultiple: UserMultipleIcon,
  UserAdd: UserAddIcon,
  UserCheck: UserCheckIcon,
  UserCircle: UserCircleIcon,
  UserList: UserListIcon,
  UserSquare: UserSquareIcon,
  Contact: ContactIcon,
  ContactRound: ContactRoundIcon,
  Handshake: HandshakeIcon,
  TeamWork: TeamWorkIcon,
  Profile: ProfileIcon,
  Group: GroupIcon,
  PersonStanding: PersonStandingIcon,
  ShoppingBag: ShoppingBagIcon,
  ShoppingCart: ShoppingCartIcon,
  ShoppingBasket: ShoppingBasketIcon,
  Store: StoreIcon,
  Gift: GiftIcon,
  Tag: TagIcon,
  Label: LabelIcon,
  Wallet: WalletIcon,
  Bank: BankIcon,
  Receipt: ReceiptIcon,
  Invoice: InvoiceIcon,
  Discount: DiscountIcon,
  DeliveryBox: DeliveryBoxIcon,
  DeliveryTruck: DeliveryTruckIcon,
  Cashier: CashierIcon,
  Coupon: CouponIcon,
  Drill: DrillIcon,
  Bulb: BulbIcon,
  Flashlight: FlashlightIcon,
  Anchor: AnchorIcon,
  Key: KeyIcon,
  Scissors: ScissorsIcon,
  Umbrella: UmbrellaIcon,
  Glasses: GlassesIcon,
  Watch: WatchIcon,
  Backpack: BackpackIcon,
  Luggage: LuggageIcon,
  Dice: DiceIcon,
  Hourglass: HourglassIcon,
  Lamp: LampIcon,
  Lantern: LanternIcon,
  Balloon: BalloonIcon,
  GameController: GameControllerIcon,
  MessageCircle: MessageCircleIcon,
  Chat: ChatIcon,
  Comment: CommentIcon,
  Megaphone: MegaphoneIcon,
  Bell: BellIcon,
  BellRing: BellRingIcon,
  Notification: NotificationIcon,
  Flag: FlagIcon,
  FlagTriangleRight: FlagTriangleRightIcon,
  Bookmark: BookmarkIcon,
  Heart: HeartIcon,
  Crown: CrownIcon,
  Medal: MedalIcon,
  Award: AwardIcon,
  Trophy: TrophyIcon,
  Diamond: DiamondIcon,
  Gem: GemIcon,
  Sparkle: SparkleIcon,
  Focus: FocusIcon,
  Goal: GoalIcon,

  BrainCircuit: BrainCircuitIcon,
  BrainCog: BrainCogIcon,
  ChatBot: ChatBotIcon,
  Robotic: RoboticIcon,
  MachineRobot: MachineRobotIcon,
  CpuCharge: CpuChargeIcon,
  NeuralNetwork: NeuralNetworkIcon,
  OnlineLearning: OnlineLearningIcon,
  Console: ConsoleIcon,
  Shell: ShellIcon,
  Bash: BashIcon,
  ComputerTerminal: ComputerTerminalIcon,
  FileTerminal: FileTerminalIcon,
  SquareTerminal: SquareTerminalIcon,
  VideoConsole: VideoConsoleIcon,
  FileScript: FileScriptIcon,
  QrCode: QrCodeIcon,
  BarCode: BarCodeIcon,
  PinCode: PinCodeIcon,
  SmsCode: SmsCodeIcon,
  Leetcode: LeetcodeIcon,
  Software: SoftwareIcon,
  Developer: DeveloperIcon,
  FileInput: FileInputIcon,
  InputText: InputTextIcon,
  NonBinary: NonBinaryIcon,
  WebDesign: WebDesignIcon,
  ApiGateway: ApiGatewayIcon,
  ArcBrowser: ArcBrowserIcon,
  FileOutput: FileOutputIcon,
  FolderCode: FolderCodeIcon,
  JavaScript: JavaScriptIcon,
  QrCodeScan: QrCodeScanIcon,
  FolderInput: FolderInputIcon,
  InspectCode: InspectCodeIcon,
  SolarSystem: SolarSystemIcon,
  AppWindowMac: AppWindowMacIcon,
  CProgramming: CProgrammingIcon,
  FolderOutput: FolderOutputIcon,
  InputNumeric: InputNumericIcon,
  SystemUpdate: SystemUpdateIcon,
  InputLongText: InputLongTextIcon,
  FileCodeCorner: FileCodeCornerIcon,
  InputShortText: InputShortTextIcon,
  InputCursorText: InputCursorTextIcon,
  SourceCodeCircle: SourceCodeCircleIcon,
  SourceCodeSquare: SourceCodeSquareIcon,
  Security: SecurityIcon,
  Shield: ShieldIcon,
  FaceId: FaceIdIcon,
  Safe: SafeIcon,
  Vault: VaultIcon,
  Gavel: GavelIcon,
  Legal: LegalIcon,
  Cctv: CctvIcon,
  ShieldUser: ShieldUserIcon,
  ShieldCog: ShieldCogIcon,
  Judge: JudgeIcon,
  Siren: SirenIcon,
  Access: AccessIcon,
  Locked: LockedIcon,
  BookKey: BookKeyIcon,
  Encrypt: EncryptIcon,
  FileKey: FileKeyIcon,
  License: LicenseIcon,
  LockKey: LockKeyIcon,
  SafeBox: SafeBoxIcon,
  ScanEye: ScanEyeIcon,
  UserKey: UserKeyIcon,
  BookLock: BookLockIcon,
  ChatLock: ChatLockIcon,
  CourtLaw: CourtLawIcon,
  DoorLock: DoorLockIcon,
  FileLock: FileLockIcon,
  KeyRound: KeyRoundIcon,
  LockOpen: LockOpenIcon,
  LockSync: LockSyncIcon,
  MailLock: MailLockIcon,
  UserLock: UserLockIcon,
  WifiLock: WifiLockIcon,
  EarthLock: EarthLockIcon,
  EyeClosed: EyeClosedIcon,
  FolderKey: FolderKeyIcon,
  Incognito: IncognitoIcon,
  KeySquare: KeySquareIcon,
  LicenseNo: LicenseNoIcon,
  PhoneLock: PhoneLockIcon,
  PoliceCap: PoliceCapIcon,
  RssLocked: RssLockedIcon,
  ShieldBan: ShieldBanIcon,
  ShieldKey: ShieldKeyIcon,
  CallLocked: CallLockedIcon,
  CctvCamera: CctvCameraIcon,
  Network: NetworkIcon,
  HardDrive: HardDriveIcon,
  MemoryStick: MemoryStickIcon,
  RamMemory: RamMemoryIcon,
  Usb: UsbIcon,
  Plug: PlugIcon,
  Fan: FanIcon,
  Cable: CableIcon,
  Drive: DriveIcon,
  Signal: SignalIcon,
  PlugZap: PlugZapIcon,
  UsbBugs: UsbBugsIcon,
  WifiCog: WifiCogIcon,
  WifiLow: WifiLowIcon,
  WifiPen: WifiPenIcon,
  CableCar: CableCarIcon,
  CloudFog: CloudFogIcon,
  EcoPower: EcoPowerIcon,
  HomeWifi: HomeWifiIcon,
  SignalNo: SignalNoIcon,
  SunCloud: SunCloudIcon,
  WifiHigh: WifiHighIcon,
  WifiSync: WifiSyncIcon,
  WifiZero: WifiZeroIcon,
  Bluetooth: BluetoothIcon,
  GpsSignal: GpsSignalIcon,
  UsbMemory: UsbMemoryIcon,
  WindPower: WindPowerIcon,
  BatteryLow: BatteryLowIcon,
  FloppyDisk: FloppyDiskIcon,
  FolderSync: FolderSyncIcon,
  FullSignal: FullSignalIcon,
  HydroPower: HydroPowerIcon,
  Abacus: AbacusIcon,
  ChartBubble: ChartBubbleIcon,
  ChartGantt: ChartGanttIcon,
  ChartRose: ChartRoseIcon,
  Flowchart: FlowchartIcon,
  Pie: PieIcon,
  Chart: ChartIcon,
  Radar: RadarIcon,
  Scale: ScaleIcon,
  Funnel: FunnelIcon,
  Spline: SplineIcon,
  ChartUp: ChartUpIcon,
  ChartDown: ChartDownIcon,
  ChartRing: ChartRingIcon,
  GridTable: GridTableIcon,
  PoolTable: PoolTableIcon,
  TableLamp: TableLampIcon,
  TableRound: TableRoundIcon,
  ChartCandle: ChartCandleIcon,
  ChartMedium: ChartMediumIcon,
  CircleGauge: CircleGaugeIcon,
  DiningTable: DiningTableIcon,
  LayoutTable: LayoutTableIcon,
  ScaleThreeD: ScaleThreeDIcon,
  WeightScale: WeightScaleIcon,
  BalanceScale: BalanceScaleIcon,
  ChartAverage: ChartAverageIcon,
  ChartBarLine: ChartBarLineIcon,
  ChartHighLow: ChartHighLowIcon,
  ChartMaximum: ChartMaximumIcon,
  ChartMinimum: ChartMinimumIcon,
  ChartNetwork: ChartNetworkIcon,
  DataRecovery: DataRecoveryIcon,
  ChartAnalysis: ChartAnalysisIcon,
  ChartDecrease: ChartDecreaseIcon,
  CameraLens: CameraLensIcon,
  CameraTripod: CameraTripodIcon,
  Aperture: ApertureIcon,
  Drone: DroneIcon,
  PictureInPicture: PictureInPictureIcon,
  ImageUp: ImageUpIcon,
  VideoAi: VideoAiIcon,
  CameraAi: CameraAiIcon,
  FilmRoll: FilmRollIcon,
  BookImage: BookImageIcon,
  DiscAlbum: DiscAlbumIcon,
  ImageCrop: ImageCropIcon,
  ImageDone: ImageDoneIcon,
  ImageDown: ImageDownIcon,
  ImagePlay: ImagePlayIcon,
  ScanImage: ScanImageIcon,
  LensConvex: LensConvexIcon,
  CameraSmile: CameraSmileIcon,
  FolderVideo: FolderVideoIcon,
  ImageDelete: ImageDeleteIcon,
  LaptopVideo: LaptopVideoIcon,
  LensConcave: LensConcaveIcon,
  TextToImage: TextToImageIcon,
  VideoReplay: VideoReplayIcon,
  ImageToVideo: ImageToVideoIcon,
  ImageUpscale: ImageUpscaleIcon,
  SwitchCamera: SwitchCameraIcon,
  CameraRotated: CameraRotatedIcon,
  ComputerVideo: ComputerVideoIcon,
  VideoCameraAi: VideoCameraAiIcon,
  InsertTopImage: InsertTopImageIcon,
  CameraNightMode: CameraNightModeIcon,
  GalleryVertical: GalleryVerticalIcon,
  ImageActualSize: ImageActualSizeIcon,
  CameraMicrophone: CameraMicrophoneIcon,
  ImageComposition: ImageCompositionIcon,
  ComputerVideoCall: ComputerVideoCallIcon,
  GalleryHorizontal: GalleryHorizontalIcon,
  GalleryThumbnails: GalleryThumbnailsIcon,
  ImageFlipVertical: ImageFlipVerticalIcon,
  InsertBottomImage: InsertBottomImageIcon,
  GalleryVerticalEnd: GalleryVerticalEndIcon,
  PictureInPictureOn: PictureInPictureOnIcon,
  CameraAutomatically: CameraAutomaticallyIcon,
  MusicNote: MusicNoteIcon,
  Speaker: SpeakerIcon,
  Headset: HeadsetIcon,
  Radio: RadioIcon,
  Guitar: GuitarIcon,
  Drum: DrumIcon,
  Volume: VolumeIcon,
  Podcast: PodcastIcon,
  Turntable: TurntableIcon,
  Playlist: PlaylistIcon,
  AudioLines: AudioLinesIcon,
  AudioWave: AudioWaveIcon,
  RadioTower: RadioTowerIcon,
  MicVocal: MicVocalIcon,
  Voice: VoiceIcon,
  BoomBox: BoomBoxIcon,
  DiscTwo: DiscTwoIcon,
  VoiceId: VoiceIdIcon,
  VolumeUp: VolumeUpIcon,
  AudioBook: AudioBookIcon,
  DiscThree: DiscThreeIcon,
  MailVoice: MailVoiceIcon,
  VolumeLow: VolumeLowIcon,
  MusicThree: MusicThreeIcon,
  VolumeHigh: VolumeHighIcon,
  CassetteTape: CassetteTapeIcon,
  VoiceComment: VoiceCommentIcon,
  RadioReceiver: RadioReceiverIcon,
  MonitorSpeaker: MonitorSpeakerIcon,
  MusicNoteSquare: MusicNoteSquareIcon,
  HeadsetConnected: HeadsetConnectedIcon,
  Restaurant: RestaurantIcon,
  Pizza: PizzaIcon,
  Cake: CakeIcon,
  IceCream: IceCreamIcon,
  Chef: ChefIcon,
  Spoon: SpoonIcon,
  Plate: PlateIcon,
  Donut: DonutIcon,
  Cookie: CookieIcon,
  Candy: CandyIcon,
  Egg: EggIcon,
  Tea: TeaIcon,
  Beer: BeerIcon,
  Cafe: CafeIcon,
  Corn: CornIcon,
  Milk: MilkIcon,
  Bread: BreadIcon,
  Drink: DrinkIcon,
  Grape: GrapeIcon,
  Honey: HoneyIcon,
  Knife: KnifeIcon,
  Sushi: SushiIcon,
  Banana: BananaIcon,
  Carrot: CarrotIcon,
  Cheese: CheeseIcon,
  Cherry: CherryIcon,
  Orange: OrangeIcon,
  TeaPod: TeaPodIcon,
  Avocado: AvocadoIcon,
  ChefHat: ChefHatIcon,
  CupSoda: CupSodaIcon,
  Dessert: DessertIcon,
  MilkOat: MilkOatIcon,
  EggFried: EggFriedIcon,
  Mushroom: MushroomIcon,
  RiceBowl: RiceBowlIcon,
  Utensils: UtensilsIcon,
  BubbleTea: BubbleTeaIcon,
  CakeSlice: CakeSliceIcon,
  CandyCane: CandyCaneIcon,
  SoftDrink: SoftDrinkIcon,
  CheeseCake: CheeseCakeIcon,
  CookingPot: CookingPotIcon,
  GlassWater: GlassWaterIcon,
  KnifeBread: KnifeBreadIcon,
  MilkBottle: MilkBottleIcon,
  MilkCarton: MilkCartonIcon,
  PillBottle: PillBottleIcon,
  StreetFood: StreetFoodIcon,
  Watermelon: WatermelonIcon,
  Health: HealthIcon,
  Hospital: HospitalIcon,
  Doctor: DoctorIcon,
  Pill: PillIcon,
  Stethoscope: StethoscopeIcon,
  Syringe: SyringeIcon,
  Ambulance: AmbulanceIcon,
  Wheelchair: WheelchairIcon,
  Thermometer: ThermometerIcon,
  Dumbbell: DumbbellIcon,
  Yoga: YogaIcon,
  HeartPulse: HeartPulseIcon,
  PillsTablet: PillsTabletIcon,
  Bandage: BandageIcon,
  Pulse: PulseIcon,
  Blood: BloodIcon,
  Vaccine: VaccineIcon,
  YogaMat: YogaMatIcon,
  BloodBag: BloodBagIcon,
  GivePill: GivePillIcon,
  Medicine: MedicineIcon,
  Swimming: SwimmingIcon,
  Wellness: WellnessIcon,
  YogaBall: YogaBallIcon,
  BloodType: BloodTypeIcon,
  BookHeart: BookHeartIcon,
  GiveBlood: GiveBloodIcon,
  HandHeart: HandHeartIcon,
  Injection: InjectionIcon,
  ScanHeart: ScanHeartIcon,
  DentalCare: DentalCareIcon,
  HeartCrack: HeartCrackIcon,
  HouseHeart: HouseHeartIcon,
  WorkoutRun: WorkoutRunIcon,
  BloodBottle: BloodBottleIcon,
  BodyPartLeg: BodyPartLegIcon,
  DentalTooth: DentalToothIcon,
  FirstAidKit: FirstAidKitIcon,
  HospitalBed: HospitalBedIcon,
  MedicalFile: MedicalFileIcon,
  MedicalMask: MedicalMaskIcon,
  SwimmingCap: SwimmingCapIcon,
  DentalBraces: DentalBracesIcon,
  EquipmentGym: EquipmentGymIcon,
  BloodPressure: BloodPressureIcon,
  CalendarHeart: CalendarHeartIcon,
  MedicineSyrup: MedicineSyrupIcon,
  BodyPartMuscle: BodyPartMuscleIcon,
  HeartHandshake: HeartHandshakeIcon,
  MedicineBottle: MedicineBottleIcon,
  School: SchoolIcon,
  University: UniversityIcon,
  Diploma: DiplomaIcon,
  Library: LibraryIcon,
  Student: StudentIcon,
  Teacher: TeacherIcon,
  Lightbulb: LightbulbIcon,
  Idea: IdeaIcon,
  Certificate: CertificateIcon,
  Honor: HonorIcon,
  Course: CourseIcon,
  SchoolBus: SchoolBusIcon,
  SchoolTie: SchoolTieIcon,
  StudyDesk: StudyDeskIcon,
  StudyLamp: StudyLampIcon,
  Translate: TranslateIcon,
  LibraryBig: LibraryBigIcon,
  SchoolBell: SchoolBellIcon,
  Whiteboard: WhiteboardIcon,
  StudentCard: StudentCardIcon,
  AlphabetThai: AlphabetThaiIcon,
  BulbCharging: BulbChargingIcon,
  GraduateMale: GraduateMaleIcon,
  NotebookTabs: NotebookTabsIcon,
  NotebookText: NotebookTextIcon,
  Presentation: PresentationIcon,
  AlphabetGreek: AlphabetGreekIcon,
  AlphabetHindi: AlphabetHindiIcon,
  GraduationCap: GraduationCapIcon,
  LanguageSkill: LanguageSkillIcon,
  SignLanguageC: SignLanguageCIcon,
  AlphabetArabic: AlphabetArabicIcon,
  AlphabetBangla: AlphabetBanglaIcon,
  AlphabetHebrew: AlphabetHebrewIcon,
  AlphabetKorean: AlphabetKoreanIcon,
  GraduateFemale: GraduateFemaleIcon,
  LanguageCircle: LanguageCircleIcon,
  LanguageSquare: LanguageSquareIcon,
  AlphabetChinese: AlphabetChineseIcon,
  GlobalEducation: GlobalEducationIcon,
  MedalFirstPlace: MedalFirstPlaceIcon,
  MedalThirdPlace: MedalThirdPlaceIcon,
  AlphabetJapanese: AlphabetJapaneseIcon,
  GraduationScroll: GraduationScrollIcon,
  MedalSecondPlace: MedalSecondPlaceIcon,
  MessageTranslate: MessageTranslateIcon,
  SchoolReportCard: SchoolReportCardIcon,
  Time: TimeIcon,
  Timer: TimerIcon,
  AlarmClock: AlarmClockIcon,
  TimeHalfPass: TimeHalfPassIcon,
  CarTime: CarTimeIcon,
  History: HistoryIcon,
  Reminder: ReminderIcon,
  TimeZone: TimeZoneIcon,
  Timeline: TimelineIcon,
  UserTime: UserTimeIcon,
  SalahTime: SalahTimeIcon,
  StopWatch: StopWatchIcon,
  AlarmSmoke: AlarmSmokeIcon,
  SmartWatch: SmartWatchIcon,
  TimerReset: TimerResetIcon,
  ViewAgenda: ViewAgendaIcon,
  Appointment: AppointmentIcon,
  CalendarCog: CalendarCogIcon,
  ClockFading: ClockFadingIcon,
  MeetingRoom: MeetingRoomIcon,
  TimeQuarter: TimeQuarterIcon,
  TimeSetting: TimeSettingIcon,
  WorkHistory: WorkHistoryIcon,
  CalendarDays: CalendarDaysIcon,
  CalendarFold: CalendarFoldIcon,
  CalendarLock: CalendarLockIcon,
  CalendarLove: CalendarLoveIcon,
  CalendarSync: CalendarSyncIcon,
  CalendarUser: CalendarUserIcon,
  DigitalClock: DigitalClockIcon,
  HangingClock: HangingClockIcon,
  TimelineList: TimelineListIcon,
  VintageClock: VintageClockIcon,
  CalendarBlock: CalendarBlockIcon,
  CalendarClock: CalendarClockIcon,
  CalendarRange: CalendarRangeIcon,
  NoMeetingRoom: NoMeetingRoomIcon,
  TimelineEvent: TimelineEventIcon,
  ClipboardClock: ClipboardClockIcon,
  TimeManagement: TimeManagementIcon,
  CalendarDateOne: CalendarDateOneIcon,
  CalendarSetting: CalendarSettingIcon,
  TimeQuarterPass: TimeQuarterPassIcon,
  CalendarAnalysis: CalendarAnalysisIcon,
  CalendarFavorite: CalendarFavoriteIcon,
  Car: CarIcon,
  Bus: BusIcon,
  Truck: TruckIcon,
  Van: VanIcon,
  Bike: BikeIcon,
  Scooter: ScooterIcon,
  Train: TrainIcon,
  Helicopter: HelicopterIcon,
  Boat: BoatIcon,
  Ship: ShipIcon,
  Taxi: TaxiIcon,
  Tractor: TractorIcon,
  Crane: CraneIcon,
  Forklift: ForkliftIcon,
  Fuel: FuelIcon,
  TrafficLight: TrafficLightIcon,
  Road: RoadIcon,
  HotAirBalloon: HotAirBalloonIcon,
  Tram: TramIcon,
  Metro: MetroIcon,
  Plane: PlaneIcon,
  Bicycle: BicycleIcon,
  BusFront: BusFrontIcon,
  CarFront: CarFrontIcon,
  Sailboat: SailboatIcon,
  TowTruck: TowTruckIcon,
  ToyTrain: ToyTrainIcon,
  Astronaut: AstronautIcon,
  CarSignal: CarSignalIcon,
  CargoShip: CargoShipIcon,
  DumpTruck: DumpTruckIcon,
  Excavator: ExcavatorIcon,
  FerryBoat: FerryBoatIcon,
  LiftTruck: LiftTruckIcon,
  PoliceCar: PoliceCarIcon,
  SemiTruck: SemiTruckIcon,
  ShipWheel: ShipWheelIcon,
  Submarine: SubmarineIcon,
  TramFront: TramFrontIcon,
  CarParking: CarParkingIcon,
  CraneTower: CraneTowerIcon,
  SpeedTrain: SpeedTrainIcon,
  TrafficJam: TrafficJamIcon,
  TrainFront: TrainFrontIcon,
  TrainTrack: TrainTrackIcon,
  FuelStation: FuelStationIcon,
  RoadWayside: RoadWaysideIcon,
  TankerTruck: TankerTruckIcon,
  TrafficCone: TrafficConeIcon,
  TruckReturn: TruckReturnIcon,
  CloudRain: CloudRainIcon,
  CloudSnow: CloudSnowIcon,
  CloudLightning: CloudLightningIcon,
  Snow: SnowIcon,
  Wind: WindIcon,
  Rainbow: RainbowIcon,
  Tornado: TornadoIcon,
  Energy: EnergyIcon,
  AtomicPower: AtomicPowerIcon,
  Rain: RainIcon,
  Sunset: SunsetIcon,
  SunSnow: SunSnowIcon,
  Sunrise: SunriseIcon,
  FastWind: FastWindIcon,
  RainDrop: RainDropIcon,
  WindSurf: WindSurfIcon,
  Avalanche: AvalancheIcon,
  BioEnergy: BioEnergyIcon,
  CloudHail: CloudHailIcon,
  EcoEnergy: EcoEnergyIcon,
  HousePlug: HousePlugIcon,
  MoonCloud: MoonCloudIcon,
  PlugSocket: PlugSocketIcon,
  SaveEnergy: SaveEnergyIcon,
  SolarPower: SolarPowerIcon,
  BatteryFull: BatteryFullIcon,
  CirclePower: CirclePowerIcon,
  FolderCloud: FolderCloudIcon,
  LaptopCloud: LaptopCloudIcon,
  PowerSocket: PowerSocketIcon,
  SolarEnergy: SolarEnergyIcon,
  SquarePower: SquarePowerIcon,
  Temperature: TemperatureIcon,
  WaterEnergy: WaterEnergyIcon,
  WindTurbine: WindTurbineIcon,
  BatteryEmpty: BatteryEmptyIcon,
  CloudBigRain: CloudBigRainIcon,
  CloudDrizzle: CloudDrizzleIcon,
  CloudMidRain: CloudMidRainIcon,
  CloudMidSnow: CloudMidSnowIcon,
  CloudSunRain: CloudSunRainIcon,
  ElectricHome: ElectricHomeIcon,
  ElectricWire: ElectricWireIcon,
  MonitorCloud: MonitorCloudIcon,
  MoonFastWind: MoonFastWindIcon,
  MoonSlowWind: MoonSlowWindIcon,
  MountainSnow: MountainSnowIcon,
  PowerService: PowerServiceIcon,
  Galaxy: GalaxyIcon,
  Comet: CometIcon,
  Cat: CatIcon,
  Lake: LakeIcon,
  Rose: RoseIcon,
  Wave: WaveIcon,
  Horse: HorseIcon,
  Panda: PandaIcon,
  Plant: PlantIcon,
  Snail: SnailIcon,
  Clover: CloverIcon,
  Desert: DesertIcon,
  EcoLab: EcoLabIcon,
  Rabbit: RabbitIcon,
  Sprout: SproutIcon,
  SunDim: SunDimIcon,
  Turtle: TurtleIcon,
  Eclipse: EclipseIcon,
  Feather: FeatherIcon,
  FirePit: FirePitIcon,
  Octopus: OctopusIcon,
  Recycle: RecycleIcon,
  SunMoon: SunMoonIcon,
  FishFood: FishFoodIcon,
  MoonStar: MoonStarIcon,
  PawPrint: PawPrintIcon,
  Squirrel: SquirrelIcon,
  TentTree: TentTreeIcon,
  TreePalm: TreePalmIcon,
  Hotel: HotelIcon,
  HospitalLocation: HospitalLocationIcon,
  Church: ChurchIcon,
  Mosque: MosqueIcon,
  Castle: CastleIcon,
  Bridge: BridgeIcon,
  Passport: PassportIcon,
  Plaza: PlazaIcon,
  EiffelTower: EiffelTowerIcon,
  BerlinTower: BerlinTowerIcon,
  TwinTower: TwinTowerIcon,
  PisaTower: PisaTowerIcon,
  Tent: TentIcon,
  Villa: VillaIcon,
  Office: OfficeIcon,
  Cottage: CottageIcon,
  Factory: FactoryIcon,
  Theater: TheaterIcon,
  Landmark: LandmarkIcon,
  Apartment: ApartmentIcon,
  HotelBell: HotelBellIcon,
  MapPinPen: MapPinPenIcon,
  NewOffice: NewOfficeIcon,
  ChinaTemple: ChinaTempleIcon,
  MapPinHouse: MapPinHouseIcon,
  MaskTheater: MaskTheaterIcon,
  OfficeChair: OfficeChairIcon,
  AlAqsaMosque: AlAqsaMosqueIcon,
  MapPinXInside: MapPinXInsideIcon,
  PassportValid: PassportValidIcon,
  PoliceStation: PoliceStationIcon,
  MosqueLocation: MosqueLocationIcon,
  PassportExpired: PassportExpiredIcon,
  Manager: ManagerIcon,
  Mentor: MentorIcon,
  Clapping: ClappingIcon,
  HandHelping: HandHelpingIcon,
  Man: ManIcon,
  Baby: BabyIcon,
  Child: ChildIcon,
  Smile: SmileIcon,
  Woman: WomanIcon,
  UserAi: UserAiIcon,
  AddTeam: AddTeamIcon,
  BabyBed: BabyBedIcon,
  UserCog: UserCogIcon,
  UserPen: UserPenIcon,
  Wedding: WeddingIcon,
  BookUser: BookUserIcon,
  ChatUser: ChatUserIcon,
  FileUser: FileUserIcon,
  ManWoman: ManWomanIcon,
  ScanFace: ScanFaceIcon,
  StarFace: StarFaceIcon,
  UserEdit: UserEditIcon,
  UserLove: UserLoveIcon,
  UserStar: UserStarIcon,
  FaceMimic: FaceMimicIcon,
  UserBlock: UserBlockIcon,
  UserStory: UserStoryIcon,
  BabyBottle: BabyBottleIcon,
  GroupItems: GroupItemsIcon,
  ContactBook: ContactBookIcon,
  UserAccount: UserAccountIcon,
  UserSharing: UserSharingIcon,
  UserFullView: UserFullViewIcon,
  UserQuestion: UserQuestionIcon,
  UserRoadside: UserRoadsideIcon,
  UserRoundCog: UserRoundCogIcon,
  UserRoundKey: UserRoundKeyIcon,
  Package: PackageIcon,
  Barcode: BarcodeIcon,
  TradeUp: TradeUpIcon,
  Contracts: ContractsIcon,
  Box: BoxIcon,
  HandBag: HandBagIcon,
  SaleTag: SaleTagIcon,
  Trolley: TrolleyIcon,
  Voucher: VoucherIcon,
  AppStore: AppStoreIcon,
  GiftCard: GiftCardIcon,
  GolfCart: GolfCartIcon,
  HotPrice: HotPriceIcon,
  ShopSign: ShopSignIcon,
  BoxingBag: BoxingBagIcon,
  PlayStore: PlayStoreIcon,
  TradeDown: TradeDownIcon,
  TradeMark: TradeMarkIcon,
  TravelBag: TravelBagIcon,
  WalletDone: WalletDoneIcon,
  BarcodeScan: BarcodeScanIcon,
  BoundingBox: BoundingBoxIcon,
  DiscountTag: DiscountTagIcon,
  MarketOrder: MarketOrderIcon,
  PackageOpen: PackageOpenIcon,
  PackageSent: PackageSentIcon,
  ReceiptText: ReceiptTextIcon,
  WalletCards: WalletCardsIcon,
  DeliverySent: DeliverySentIcon,
  DeliveryView: DeliveryViewIcon,
  JusticeScale: JusticeScaleIcon,
  SafeDelivery: SafeDeliveryIcon,
  CouponPercent: CouponPercentIcon,
  DeliveryDelay: DeliveryDelayIcon,
  PackageMoving: PackageMovingIcon,
  StoreLocation: StoreLocationIcon,
  TruckDelivery: TruckDeliveryIcon,
  DeliveryReturn: DeliveryReturnIcon,
  DeliverySecure: DeliverySecureIcon,
  MarketAnalysis: MarketAnalysisIcon,
  PackageProcess: PackageProcessIcon,
  StoreManagement: StoreManagementIcon,
  DeliveryTracking: DeliveryTrackingIcon,
  PackageDelivered: PackageDeliveredIcon,
  ThumbsUp: ThumbsUpIcon,
  Ranking: RankingIcon,
  Ribbon: RibbonIcon,
  FileStar: FileStarIcon,
  Progress: ProgressIcon,
  StarHalf: StarHalfIcon,
  Favourite: FavouriteIcon,
  MapPinned: MapPinnedIcon,
  Milestone: MilestoneIcon,
  StackStar: StackStarIcon,
  StarAward: StarAwardIcon,
  FocusPoint: FocusPointIcon,
  HonourStar: HonourStarIcon,
  RacingFlag: RacingFlagIcon,
  StarCircle: StarCircleIcon,
  StarSquare: StarSquareIcon,
  AllBookmark: AllBookmarkIcon,
  FallingStar: FallingStarIcon,
  BookBookmark: BookBookmarkIcon,
  FileBookmark: FileBookmarkIcon,
  LaurelWreath: LaurelWreathIcon,
  ThumbsUpDown: ThumbsUpDownIcon,
  FileFavourite: FileFavouriteIcon,
  CursorProgress: CursorProgressIcon,
  DiamondPercent: DiamondPercentIcon,
  FavouriteCircle: FavouriteCircleIcon,
  FavouriteSquare: FavouriteSquareIcon,
  ThumbsUpEllipse: ThumbsUpEllipseIcon,
  FlagTriangleLeft: FlagTriangleLeftIcon,
  LaurelWreathLeft: LaurelWreathLeftIcon,
  LaurelWreathFirst: LaurelWreathFirstIcon,
  LaurelWreathRight: LaurelWreathRightIcon,
  ThumbsUpRectangle: ThumbsUpRectangleIcon,
  BubbleChatFavourite: BubbleChatFavouriteIcon,
  CollectionsBookmark: CollectionsBookmarkIcon,
  LeftToRightListStar: LeftToRightListStarIcon,
  ShoppingBagFavorite: ShoppingBagFavoriteIcon,
  ShoppingCartFavorite: ShoppingCartFavoriteIcon,
  ShoppingBasketFavorite: ShoppingBasketFavoriteIcon,
  Gamepad: GamepadIcon,
  Joystick: JoystickIcon,
  Chess: ChessIcon,
  Football: FootballIcon,
  Basketball: BasketballIcon,
  Bowling: BowlingIcon,
  Baseball: BaseballIcon,
  Volleyball: VolleyballIcon,
  PartyPopper: PartyPopperIcon,
  Kite: KiteIcon,
  MagicWand: MagicWandIcon,
  Ski: SkiIcon,
  Game: GameIcon,
  Party: PartyIcon,
  Domino: DominoIcon,
  SdCard: SdCardIcon,
  CardSim: CardSimIcon,
  GolfBat: GolfBatIcon,
  GolfBall: GolfBallIcon,
  GolfHole: GolfHoleIcon,
  ToyBrick: ToyBrickIcon,
  BlockGame: BlockGameIcon,
  ChessKing: ChessKingIcon,
  ChessPawn: ChessPawnIcon,
  ChessRook: ChessRookIcon,
  DiceFaces: DiceFacesIcon,
  Fireworks: FireworksIcon,
  ChessQueen: ChessQueenIcon,
  MasterCard: MasterCardIcon,
  TennisBall: TennisBallIcon,
  BaseballBat: BaseballBatIcon,
  BowlingBall: BowlingBallIcon,
  BowlingPins: BowlingPinsIcon,
  ChessBishop: ChessBishopIcon,
  ChessKnight: ChessKnightIcon,
  TennisRacket: TennisRacketIcon,
  FootballPitch: FootballPitchIcon,
  BaseballHelmet: BaseballHelmetIcon,
  BasketballHoop: BasketballHoopIcon,
  TableTennisBat: TableTennisBatIcon,
  AmericanFootball: AmericanFootballIcon,
  LicenseThirdParty: LicenseThirdPartyIcon,
  GamepadDirectional: GamepadDirectionalIcon,
  CursorMagicSelection: CursorMagicSelectionIcon,
  TestTube: TestTubeIcon,
  Anvil: AnvilIcon,
  Prism: PrismIcon,
  WaterPump: WaterPumpIcon,
  PetrolPump: PetrolPumpIcon,
  Nut: NutIcon,
  Pi: PiIcon,
  Cog: CogIcon,
  Bolt: BoltIcon,
  Math: MathIcon,
  Sigma: SigmaIcon,
  GasPipe: GasPipeIcon,
  Bacteria: BacteriaIcon,
  HalalLab: HalalLabIcon,
  InsertPi: InsertPiIcon,
  RemovePi: RemovePiIcon,
  BoardMath: BoardMathIcon,
  Chemistry: ChemistryIcon,
  FlaskRound: FlaskRoundIcon,
  ColumnsThreeCog: ColumnsThreeCogIcon,
  TestTubeDiagonal: TestTubeDiagonalIcon,
  Pen: PenIcon,
  Path: PathIcon,
  Text: TextIcon,
  Type: TypeIcon,
  Wand: WandIcon,
  Frame: FrameIcon,
  Lasso: LassoIcon,
  Layer: LayerIcon,
  Sketch: SketchIcon,
  Compass: CompassIcon,
  PenLine: PenLineIcon,
  Sticker: StickerIcon,
  BookType: BookTypeIcon,
  ScanText: ScanTextIcon,
  TextBold: TextBoldIcon,
  TextFont: TextFontIcon,
  FolderPen: FolderPenIcon,
  LassoTool: LassoToolIcon,
  TabletPen: TabletPenIcon,
  TextClear: TextClearIcon,
  TextColor: TextColorIcon,
  TextQuote: TextQuoteIcon,
  BlushBrush: BlushBrushIcon,
  LayersLogo: LayersLogoIcon,
  PaintBoard: PaintBoardIcon,
  PencilLine: PencilLineIcon,
  TextCircle: TextCircleIcon,
  TextItalic: TextItalicIcon,
  TextSelect: TextSelectIcon,
  DrawingMode: DrawingModeIcon,
  LassoSelect: LassoSelectIcon,
  NotepadText: NotepadTextIcon,
  PaintBucket: PaintBucketIcon,
  PaintRoller: PaintRollerIcon,
  PencilRuler: PencilRulerIcon,
  TextAllCaps: TextAllCapsIcon,
  Phone: PhoneIcon,
  Call: CallIcon,
  Rss: RssIcon,
  AtSign: AtSignIcon,
  Speech: SpeechIcon,
  CallEnd: CallEndIcon,
  Hashtag: HashtagIcon,
  Mailbox: MailboxIcon,
  Message: MessageIcon,
  CallDone: CallDoneIcon,
  ChatDone: ChatDoneIcon,
  ChatEdit: ChatEditIcon,
  MailEdit: MailEditIcon,
  MailLove: MailLoveIcon,
  MailSend: MailSendIcon,
  CallSpark: CallSparkIcon,
  ChatDelay: ChatDelayIcon,
  ChatSpark: ChatSparkIcon,
  FlipPhone: FlipPhoneIcon,
  HoldPhone: HoldPhoneIcon,
  MailBlock: MailBlockIcon,
  MailReply: MailReplyIcon,
  PhoneCall: PhoneCallIcon,
  Voicemail: VoicemailIcon,
  CallMissed: CallMissedIcon,
  CallPaused: CallPausedIcon,
  ChatIncome: ChatIncomeIcon,
  MailAtSign: MailAtSignIcon,
  PhoneShake: PhoneShakeIcon,
  SmartPhone: SmartPhoneIcon,
  CallRinging: CallRingingIcon,
  ChatOutcome: ChatOutcomeIcon,
  ChatPreview: ChatPreviewIcon,
  InboxUnread: InboxUnreadIcon,
  MailAccount: MailAccountIcon,
  MessageDone: MessageDoneIcon,
  MessageEdit: MessageEditIcon,
  MessageLock: MessageLockIcon,
  FileCog: FileCogIcon,
  FilePin: FilePinIcon,
  FileZip: FileZipIcon,
  FilePlay: FilePlayIcon,
  FileScan: FileScanIcon,
  FileSync: FileSyncIcon,
  FileType: FileTypeIcon,
  HtmlFile: HtmlFileIcon,
  FileAudio: FileAudioIcon,
  FileBlock: FileBlockIcon,
  FileClock: FileClockIcon,
  FileCloud: FileCloudIcon,
  FileDigit: FileDigitIcon,
  FileEmpty: FileEmptyIcon,
  FileHeart: FileHeartIcon,
  FileImage: FileImageIcon,
  FileMusic: FileMusicIcon,
  FilePaste: FilePasteIcon,
  FileStack: FileStackIcon,
  FileVideo: FileVideoIcon,
  FolderCog: FolderCogIcon,
  FolderDot: FolderDotIcon,
  FolderPin: FolderPinIcon,
  FolderZip: FolderZipIcon,
  FileBraces: FileBracesIcon,
  FileLocked: FileLockedIcon,
  FolderLock: FolderLockIcon,
  FolderRoot: FolderRootIcon,
  FolderTree: FolderTreeIcon,
  FilePenLine: FilePenLineIcon,
  FileXCorner: FileXCornerIcon,
  FolderAudio: FolderAudioIcon,
  FolderBlock: FolderBlockIcon,
  FolderClock: FolderClockIcon,
  FolderHeart: FolderHeartIcon,
  FolderMusic: FolderMusicIcon,
  FileChartPie: FileChartPieIcon,
  Printer: PrinterIcon,
  StickyNote: StickyNoteIcon,
  Eraser: EraserIcon,
  Highlighter: HighlighterIcon,
  Desk: DeskIcon,
  Stamp: StampIcon,
  TapeMeasure: TapeMeasureIcon,
  SwatchBook: SwatchBookIcon,
  Id: IdIcon,
  Form: FormIcon,
  Note: NoteIcon,
  BookA: BookAIcon,
  BookDown: BookDownIcon,
  BookEdit: BookEditIcon,
  CookBook: CookBookIcon,
  NoteDone: NoteDoneIcon,
  NoteEdit: NoteEditIcon,
  BookUpTwo: BookUpTwoIcon,
  BookDashed: BookDashedIcon,
  BookMarked: BookMarkedIcon,
  BookOpenText: BookOpenTextIcon,
  LegalDocument: LegalDocumentIcon,
  PenConnectUsb: PenConnectUsbIcon,
  PrinterThreeD: PrinterThreeDIcon,
  ClipboardPaste: ClipboardPasteIcon,
  AttachmentCircle: AttachmentCircleIcon,
  AttachmentSquare: AttachmentSquareIcon,
  ClipboardPenLine: ClipboardPenLineIcon,
  DocumentAttachment: DocumentAttachmentIcon,
  DocumentValidation: DocumentValidationIcon,
  Bucket: BucketIcon,
  Shovel: ShovelIcon,
  Axe: AxeIcon,
  HatGlasses: HatGlassesIcon,
  Purse: PurseIcon,
  BendTool: BendToolIcon,
  LampDesk: LampDeskIcon,
  Necklace: NecklaceIcon,
  WallLamp: WallLampIcon,
  LampFloor: LampFloorIcon,
  SafetyPin: SafetyPinIcon,
  VrGlasses: VrGlassesIcon,
  LampWallUp: LampWallUpIcon,
  LicensePin: LicensePinIcon,
  RollingPin: RollingPinIcon,
  AnchorPoint: AnchorPointIcon,
  FishingHook: FishingHookIcon,
  LampCeiling: LampCeilingIcon,
  LegalHammer: LegalHammerIcon,
  PinLocation: PinLocationIcon,
  PocketKnife: PocketKnifeIcon,
  WavesLadder: WavesLadderIcon,
  ArtboardTool: ArtboardToolIcon,
  IceCreamBowl: IceCreamBowlIcon,
  LampWallDown: LampWallDownIcon,
  OlympicTorch: OlympicTorchIcon,
  BrushCleaning: BrushCleaningIcon,
  SpoonAndKnife: SpoonAndKnifeIcon,
  CleaningBucket: CleaningBucketIcon,
  DraftingCompass: DraftingCompassIcon,
};

registerExtendedIcons(EXTENDED_ICON_MAP);
