import type { IconSvgElement } from "@hugeicons/react";
import {
  AddressBookIcon,
  AiBrowserIcon,
  AiContentGenerator01Icon,
  AlbumIcon,
  AlgorithmIcon,
  AnalyticsDownIcon,
  AnalyticsIcon,
  AnalyticsUpIcon,
  AnchorIcon,
  AntennaIcon,
  ApiIcon,
  ArrowDown02Icon,
  ArrowDownDoubleIcon,
  ArrowMoveDownLeftIcon,
  ArrowMoveDownRightIcon,
  ArrowReloadHorizontalIcon,
  ArrowRight02Icon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  ArrowUp01Icon,
  ArrowUp02Icon,
  ArrowUpDoubleIcon,
  ArrowUpDownIcon,
  ArrowUpRight01Icon,
  ArtboardIcon,
  AsteroidIcon,
  AtomIcon,
  AttachmentIcon,
  AudioWaveformIcon,
  AwardIcon,
  BackpackIcon,
  BalloonIcon,
  BankIcon,
  BarChartIcon,
  BatteryChargingIcon,
  BatteryIcon,
  BeachIcon,
  BellDotIcon,
  BellIcon,
  BellRingIcon,
  BinaryCodeIcon,
  BinaryIcon,
  BirdIcon,
  BlockchainIcon,
  BluetoothConnectedIcon,
  BlurIcon,
  Book02Icon,
  BookIcon,
  BookmarkIcon,
  BookOpenIcon,
  BookshelfIcon,
  BooksIcon,
  BookTextIcon,
  BracketsIcon,
  BrainIcon,
  BriefcaseIcon,
  BrowserIcon,
  BrushIcon,
  BuildingIcon,
  BulbIcon,
  CactusIcon,
  CalculatorIcon,
  Calendar03Icon,
  CalendarCheckOut02Icon,
  CameraIcon,
  CameraVideoIcon,
  CanvasIcon,
  CashierIcon,
  ChartAreaIcon,
  ChartBarBigIcon,
  ChartColumnIcon,
  ChartLineIcon,
  ChartRadarIcon,
  ChartScatterIcon,
  ChartSplineIcon,
  ChatIcon,
  ChipIcon,
  CircleArrowShrink01Icon,
  CircuitBoardIcon,
  CityIcon,
  ClapperboardIcon,
  CleanIcon,
  ClipboardIcon,
  ClipboardListIcon,
  Clock01Icon,
  CloudBackupIcon,
  CloudCogIcon,
  CloudIcon,
  CloudOffIcon,
  CloudServerIcon,
  CloudSyncIcon,
  CodeCircleIcon,
  CodeFolderIcon,
  CodeSimpleIcon,
  CodeSquareIcon,
  CodeXmlIcon,
  Coffee02Icon,
  CollapseIcon,
  ColorPickerIcon,
  CommandIcon,
  CommandLineIcon,
  CommentIcon,
  ComputerEthernetIcon,
  ContactIcon,
  ContactRoundIcon,
  ContrastIcon,
  CouponIcon,
  CpuIcon,
  CropIcon,
  CrownIcon,
  DashboardCircleIcon,
  DashedLine02Icon,
  DatabaseIcon,
  DateTimeIcon,
  DeliveryBoxIcon,
  DeliveryTruckIcon,
  DiamondIcon,
  DiceIcon,
  DiscIcon,
  DiscordIcon,
  DiscountIcon,
  DnaIcon,
  DocumentCodeIcon,
  DragDropHorizontalIcon,
  DragDropVerticalIcon,
  DrillIcon,
  DropletIcon,
  EarthIcon,
  Edit04Icon,
  ElectricPlugsIcon,
  EngineIcon,
  ExpandIcon,
  File01Icon,
  FileAddIcon,
  FileArchiveIcon,
  FileAttachmentIcon,
  FileBoxIcon,
  FileCheckIcon,
  FileCodeIcon,
  FileEditIcon,
  FileEmpty02Icon,
  FilePenIcon,
  FileQuestionMarkIcon,
  FileSearchIcon,
  FilmIcon,
  FireIcon,
  FirewallIcon,
  FishIcon,
  FlagIcon,
  FlagTriangleRightIcon,
  FlameIcon,
  FlashlightIcon,
  FlaskConicalIcon,
  FlowerIcon,
  FocusIcon,
  Folder02Icon,
  FolderEditIcon,
  FolderRemoveIcon,
  FunctionIcon,
  FunctionSquareIcon,
  GameControllerIcon,
  GaugeIcon,
  GearsIcon,
  GemIcon,
  GiftIcon,
  GitBranchIcon,
  GitForkIcon,
  GithubIcon,
  GitMergeIcon,
  GitPullRequestArrow,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  GlassesIcon,
  GlobeLockIcon,
  GoalIcon,
  GravityIcon,
  GridViewIcon,
  GroupIcon,
  HammerIcon,
  HandshakeIcon,
  HeadphonesIcon,
  HeartIcon,
  HomeIcon,
  HourglassIcon,
  HouseIcon,
  ImageIcon,
  InboxIcon,
  InfinityIcon,
  InternetIcon,
  InvoiceIcon,
  IslandIcon,
  KeyboardIcon,
  KeyIcon,
  LabelIcon,
  LampIcon,
  LanternIcon,
  LaptopIcon,
  Layers01Icon,
  LayoutTwoColumnIcon,
  LayoutTwoRowIcon,
  LeafIcon,
  LeafyGreenIcon,
  LighthouseIcon,
  LimitationIcon,
  LinkSquare02Icon,
  ListViewIcon,
  LocationIcon,
  LockIcon,
  LuggageIcon,
  MagnetIcon,
  Mail02Icon,
  MailOpen01Icon,
  MapIcon,
  MapPinIcon,
  McpServerIcon,
  MedalIcon,
  MegaphoneIcon,
  Menu02Icon,
  MessageAdd02Icon,
  MessageCircleIcon,
  Mic02Icon,
  MicrochipIcon,
  MicroscopeIcon,
  MoleculesIcon,
  MonitorIcon,
  MoonIcon,
  MountainIcon,
  MouseIcon,
  MusicIcon,
  NotebookIcon,
  NotificationIcon,
  NuclearPowerIcon,
  OpenSourceIcon,
  PackageReceiveIcon,
  PaintBrushIcon,
  PauseIcon,
  PencilIcon,
  PenToolIcon,
  PercentIcon,
  PersonStandingIcon,
  PhysicsIcon,
  PickaxeIcon,
  PieChartIcon,
  PineTreeIcon,
  PinIcon,
  PinOffIcon,
  PlayIcon,
  PlusMinusSquare01Icon,
  PlusSignIcon,
  PowerIcon,
  ProfileIcon,
  PuzzleIcon,
  RadiationIcon,
  ReceiptIcon,
  Refresh01Icon,
  RepeatIcon,
  RobotIcon,
  RocketIcon,
  RouterIcon,
  RulerIcon,
  SatelliteDishIcon,
  SatelliteIcon,
  ScissorsIcon,
  SecurityCheckIcon,
  SentIcon,
  ServerCogIcon,
  ServerIcon,
  ShoppingBagIcon,
  ShoppingBasketIcon,
  ShoppingCartIcon,
  SidebarBottomIcon,
  SidebarRightIcon,
  SmartPhone01Icon,
  Sorting01Icon,
  SparkleIcon,
  SquareIcon,
  SquareUnlock02Icon,
  StarIcon,
  StoreIcon,
  SunIcon,
  TableIcon,
  TagIcon,
  TeamWorkIcon,
  TelescopeIcon,
  TestTube01Icon,
  TextWrapIcon,
  TimeScheduleIcon,
  TreeIcon,
  TrophyIcon,
  UmbrellaIcon,
  Unarchive03Icon,
  UserAddIcon,
  UserCheckIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserListIcon,
  UserMultipleIcon,
  UsersIcon,
  UserSquareIcon,
  VideoIcon,
  ViewIcon,
  ViewOffIcon,
  WalletIcon,
  WatchIcon,
  WifiIcon,
  WrenchIcon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
} from "@hugeicons/core-free-icons";
import { type ExtendedIconMap, registerExtendedIcons } from "./icon-registry";

const PaletteStrokeRoundedIcon: IconSvgElement = [
  [
    "path",
    {
      d: "M21.8205 10.4127C22.062 11.8519 22.1827 12.5715 21.2423 13.9326C21.1459 14.0722 20.8966 14.3713 20.777 14.4911C19.6103 15.6586 18.4308 15.6586 16.0716 15.6586H14.1392C13.5085 15.6586 13.1931 15.6586 12.9639 15.7142C11.9586 15.9581 11.3031 16.9391 11.453 17.9755C11.4872 18.2118 11.6043 18.5085 11.8386 19.102C11.9345 19.3449 11.9824 19.4664 12.0136 19.7304C12.1292 20.7084 11.0869 21.9508 10.1158 21.9926C9.85358 22.0039 9.83681 22.0002 9.80326 21.9926C7.66174 21.51 5.66204 20.3123 4.18389 18.4421C0.736789 14.0808 1.43146 7.71364 5.73548 4.22064C10.0395 0.727643 16.323 1.43156 19.7701 5.79289C20.868 7.1819 21.5457 8.77438 21.8205 10.4127Z",
      fill: "none",
      fillRule: "evenodd",
      clipRule: "evenodd",
      stroke: "currentColor",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "0",
    },
  ],
  [
    "path",
    {
      d: "M7.36719 7.74976H7.24219M7.49219 7.74976C7.49219 7.88783 7.38026 7.99976 7.24219 7.99976C7.10412 7.99976 6.99219 7.88783 6.99219 7.74976C6.99219 7.61169 7.10412 7.49976 7.24219 7.49976C7.38026 7.49976 7.49219 7.61169 7.49219 7.74976Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "1",
    },
  ],
  [
    "path",
    {
      d: "M7.36719 15.7498H7.24219M7.49219 15.7498C7.49219 15.8878 7.38026 15.9998 7.24219 15.9998C7.10412 15.9998 6.99219 15.8878 6.99219 15.7498C6.99219 15.6117 7.10412 15.4998 7.24219 15.4998C7.38026 15.4998 7.49219 15.6117 7.49219 15.7498Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "2",
    },
  ],
  [
    "path",
    {
      d: "M11.8672 5.74976H11.7422M11.9922 5.74976C11.9922 5.88783 11.8803 5.99976 11.7422 5.99976C11.6041 5.99976 11.4922 5.88783 11.4922 5.74976C11.4922 5.61169 11.6041 5.49976 11.7422 5.49976C11.8803 5.49976 11.9922 5.61169 11.9922 5.74976Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "3",
    },
  ],
  [
    "path",
    {
      d: "M16.3672 7.74976H16.2422M16.4922 7.74976C16.4922 7.88783 16.3803 7.99976 16.2422 7.99976C16.1041 7.99976 15.9922 7.88783 15.9922 7.74976C15.9922 7.61169 16.1041 7.49976 16.2422 7.49976C16.3803 7.49976 16.4922 7.61169 16.4922 7.74976Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "4",
    },
  ],
  [
    "path",
    {
      d: "M18.3672 11.7498H18.2422M18.4922 11.7498C18.4922 11.8878 18.3803 11.9998 18.2422 11.9998C18.1041 11.9998 17.9922 11.8878 17.9922 11.7498C17.9922 11.6117 18.1041 11.4998 18.2422 11.4998C18.3803 11.4998 18.4922 11.6117 18.4922 11.7498Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "5",
    },
  ],
  [
    "path",
    {
      d: "M5.86719 11.7498H5.74219M5.99219 11.7498C5.99219 11.8878 5.88026 11.9998 5.74219 11.9998C5.60412 11.9998 5.49219 11.8878 5.49219 11.7498C5.49219 11.6117 5.60412 11.4998 5.74219 11.4998C5.88026 11.4998 5.99219 11.6117 5.99219 11.7498Z",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "1.5",
      key: "6",
    },
  ],
];

export const EXTENDED_ICON_MAP: ExtendedIconMap = {
  AiBrowser: AiBrowserIcon,
  AiContentGenerator01: AiContentGenerator01Icon,
  AlignLeft: Menu02Icon,
  AppWindow: BrowserIcon,
  ArchiveRestore: Unarchive03Icon,
  ArrowDown: ArrowDown02Icon,
  ArrowRight: ArrowRight02Icon,
  ArrowReloadHorizontal: ArrowReloadHorizontalIcon,
  ArrowUp: ArrowUp02Icon,
  ArrowUpDown: ArrowUpDownIcon,
  ArrowTurnBackward: ArrowTurnBackwardIcon,
  ArrowTurnForward: ArrowTurnForwardIcon,
  ArrowUpRight: ArrowUpRight01Icon,
  Beaker: TestTube01Icon,
  BellDot: BellDotIcon,
  Browser: BrowserIcon,
  Brain: BrainIcon,
  Calendar: Calendar03Icon,
  CalendarCheckOut02: CalendarCheckOut02Icon,
  ChartColumn: ChartColumnIcon,
  ChevronUp: ArrowUp01Icon,
  ChevronsDown: ArrowDownDoubleIcon,
  ChevronsUp: ArrowUpDoubleIcon,
  CircleArrowShrink: CircleArrowShrink01Icon,
  Clean: CleanIcon,
  Clock: Clock01Icon,
  Cloud: CloudIcon,
  CloudOff: CloudOffIcon,
  Coffee: Coffee02Icon,
  Columns2: LayoutTwoColumnIcon,
  CornerDownLeft: ArrowMoveDownLeftIcon,
  CornerDownRight: ArrowMoveDownRightIcon,
  Discord: DiscordIcon,
  DateTime: DateTimeIcon,
  Github: GithubIcon,
  DragDropHorizontal: DragDropHorizontalIcon,
  DragDropVertical: DragDropVerticalIcon,
  EditFile: Edit04Icon,
  ElectricPlugs: ElectricPlugsIcon,
  Eye: ViewIcon,
  EyeOff: ViewOffIcon,
  Explore: Book02Icon,
  ExternalLink: LinkSquare02Icon,
  FileDiff: PlusMinusSquare01Icon,
  File: FileEmpty02Icon,
  FileAttachment: FileAttachmentIcon,
  FileQuestion: FileQuestionMarkIcon,
  FileText: File01Icon,
  FolderOpen: Folder02Icon,
  FolderEdit: FolderEditIcon,
  FolderMinus: FolderRemoveIcon,
  Fork: GitForkIcon,
  GitBranch: GitBranchIcon,
  GitMerge: GitMergeIcon,
  GitPullRequest: GitPullRequestIcon,
  GitPullRequestArrow: GitPullRequestArrow,
  GitPullRequestClosed: GitPullRequestClosedIcon,
  GitPullRequestDraft: GitPullRequestDraftIcon,
  Globe: InternetIcon,
  GridView: GridViewIcon,
  Laptop: LaptopIcon,
  Layers: Layers01Icon,
  Limitation: LimitationIcon,
  ListView: ListViewIcon,
  Lock: LockIcon,
  Mail: Mail02Icon,
  MailOpen: MailOpen01Icon,
  Maximize2: ExpandIcon,
  Mic: Mic02Icon,
  Minimize2: CollapseIcon,
  NewTab: DashedLine02Icon,
  PackageReceive: PackageReceiveIcon,
  Palette: PaletteStrokeRoundedIcon,
  PanelBottom: SidebarBottomIcon,
  PanelRight: SidebarRightIcon,
  Paperclip: AttachmentIcon,
  Pause: PauseIcon,
  Pin: PinIcon,
  PinOff: PinOffIcon,
  Play: PlayIcon,
  Plus: PlusSignIcon,
  Puzzle: PuzzleIcon,
  Repeat: RepeatIcon,
  SecurityCheck: SecurityCheckIcon,
  RotateCcw: Refresh01Icon,
  Rows2: LayoutTwoRowIcon,
  Sent: SentIcon,
  SideChat: MessageAdd02Icon,
  Smartphone: SmartPhone01Icon,
  Sort: Sorting01Icon,
  Square: SquareIcon,
  SquareUnlock02: SquareUnlock02Icon,
  Star: StarIcon,
  TextWrap: TextWrapIcon,
  TimeSchedule: TimeScheduleIcon,
  UserRound: UserIcon,
  ZoomIn: ZoomInAreaIcon,
  ZoomOut: ZoomOutAreaIcon,

  CodeSimple: CodeSimpleIcon,
  CodeCircle: CodeCircleIcon,
  CodeSquare: CodeSquareIcon,
  CodeXml: CodeXmlIcon,
  CodeFolder: CodeFolderIcon,
  DocumentCode: DocumentCodeIcon,
  FileCode: FileCodeIcon,
  Command: CommandIcon,
  CommandLine: CommandLineIcon,
  Function: FunctionIcon,
  FunctionSquare: FunctionSquareIcon,
  Algorithm: AlgorithmIcon,
  Binary: BinaryIcon,
  BinaryCode: BinaryCodeIcon,
  Brackets: BracketsIcon,
  Api: ApiIcon,
  McpServer: McpServerIcon,
  Keyboard: KeyboardIcon,
  Mouse: MouseIcon,
  Monitor: MonitorIcon,
  Cpu: CpuIcon,
  Robot: RobotIcon,
  OpenSource: OpenSourceIcon,
  CircuitBoard: CircuitBoardIcon,
  CloudServer: CloudServerIcon,
  CloudCog: CloudCogIcon,
  CloudSync: CloudSyncIcon,
  CloudBackup: CloudBackupIcon,
  Database: DatabaseIcon,
  Server: ServerIcon,
  ServerCog: ServerCogIcon,
  Microchip: MicrochipIcon,
  Chip: ChipIcon,
  ComputerEthernet: ComputerEthernetIcon,
  BluetoothConnected: BluetoothConnectedIcon,
  Wifi: WifiIcon,
  Router: RouterIcon,
  Antenna: AntennaIcon,
  Satellite: SatelliteIcon,
  SatelliteDish: SatelliteDishIcon,
  Firewall: FirewallIcon,
  GlobeLock: GlobeLockIcon,
  Battery: BatteryIcon,
  BatteryCharging: BatteryChargingIcon,
  Power: PowerIcon,
  Blockchain: BlockchainIcon,
  FileQuestionMark: FileQuestionMarkIcon,
  FileAdd: FileAddIcon,
  FileCheck: FileCheckIcon,
  FileEdit: FileEditIcon,
  FileSearch: FileSearchIcon,
  FileArchive: FileArchiveIcon,
  FileBox: FileBoxIcon,
  FilePen: FilePenIcon,
  Clipboard: ClipboardIcon,
  ClipboardList: ClipboardListIcon,
  Notebook: NotebookIcon,
  Book: BookIcon,
  BookOpen: BookOpenIcon,
  BookText: BookTextIcon,
  Books: BooksIcon,
  Bookshelf: BookshelfIcon,
  Inbox: InboxIcon,
  Briefcase: BriefcaseIcon,
  AddressBook: AddressBookIcon,
  Analytics: AnalyticsIcon,
  AnalyticsUp: AnalyticsUpIcon,
  AnalyticsDown: AnalyticsDownIcon,
  BarChart: BarChartIcon,
  ChartLine: ChartLineIcon,
  ChartArea: ChartAreaIcon,
  ChartBarBig: ChartBarBigIcon,
  ChartScatter: ChartScatterIcon,
  ChartRadar: ChartRadarIcon,
  ChartSpline: ChartSplineIcon,
  PieChart: PieChartIcon,
  DashboardCircle: DashboardCircleIcon,
  Gauge: GaugeIcon,
  Percent: PercentIcon,
  Table: TableIcon,
  Brush: BrushIcon,
  PaintBrush: PaintBrushIcon,
  ColorPicker: ColorPickerIcon,
  Image: ImageIcon,
  Camera: CameraIcon,
  CameraVideo: CameraVideoIcon,
  Video: VideoIcon,
  Music: MusicIcon,
  AudioWaveform: AudioWaveformIcon,
  Headphones: HeadphonesIcon,
  Film: FilmIcon,
  Album: AlbumIcon,
  Disc: DiscIcon,
  Artboard: ArtboardIcon,
  PenTool: PenToolIcon,
  Pencil: PencilIcon,
  Ruler: RulerIcon,
  Crop: CropIcon,
  Contrast: ContrastIcon,
  Blur: BlurIcon,
  Canvas: CanvasIcon,
  Clapperboard: ClapperboardIcon,
  Atom: AtomIcon,
  FlaskConical: FlaskConicalIcon,
  Microscope: MicroscopeIcon,
  Telescope: TelescopeIcon,
  Dna: DnaIcon,
  Molecules: MoleculesIcon,
  Physics: PhysicsIcon,
  Calculator: CalculatorIcon,
  Gears: GearsIcon,
  Magnet: MagnetIcon,
  Radiation: RadiationIcon,
  Rocket: RocketIcon,
  Gravity: GravityIcon,
  Infinity: InfinityIcon,
  Engine: EngineIcon,
  Hammer: HammerIcon,
  Wrench: WrenchIcon,
  Asteroid: AsteroidIcon,
  NuclearPower: NuclearPowerIcon,
  Pickaxe: PickaxeIcon,
  Tree: TreeIcon,
  Leaf: LeafIcon,
  LeafyGreen: LeafyGreenIcon,
  Flower: FlowerIcon,
  Cactus: CactusIcon,
  PineTree: PineTreeIcon,
  Mountain: MountainIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Droplet: DropletIcon,
  Fire: FireIcon,
  Flame: FlameIcon,
  Earth: EarthIcon,
  Map: MapIcon,
  MapPin: MapPinIcon,
  Location: LocationIcon,
  Home: HomeIcon,
  House: HouseIcon,
  Building: BuildingIcon,
  City: CityIcon,
  Beach: BeachIcon,
  Island: IslandIcon,
  Fish: FishIcon,
  Bird: BirdIcon,
  Lighthouse: LighthouseIcon,
  Users: UsersIcon,
  UserGroup: UserGroupIcon,
  UserMultiple: UserMultipleIcon,
  UserAdd: UserAddIcon,
  UserCheck: UserCheckIcon,
  UserCircle: UserCircleIcon,
  UserList: UserListIcon,
  UserSquare: UserSquareIcon,
  Contact: ContactIcon,
  ContactRound: ContactRoundIcon,
  Handshake: HandshakeIcon,
  TeamWork: TeamWorkIcon,
  Profile: ProfileIcon,
  Group: GroupIcon,
  PersonStanding: PersonStandingIcon,
  ShoppingBag: ShoppingBagIcon,
  ShoppingCart: ShoppingCartIcon,
  ShoppingBasket: ShoppingBasketIcon,
  Store: StoreIcon,
  Gift: GiftIcon,
  Tag: TagIcon,
  Label: LabelIcon,
  Wallet: WalletIcon,
  Bank: BankIcon,
  Receipt: ReceiptIcon,
  Invoice: InvoiceIcon,
  Discount: DiscountIcon,
  DeliveryBox: DeliveryBoxIcon,
  DeliveryTruck: DeliveryTruckIcon,
  Cashier: CashierIcon,
  Coupon: CouponIcon,
  Drill: DrillIcon,
  Bulb: BulbIcon,
  Flashlight: FlashlightIcon,
  Anchor: AnchorIcon,
  Key: KeyIcon,
  Scissors: ScissorsIcon,
  Umbrella: UmbrellaIcon,
  Glasses: GlassesIcon,
  Watch: WatchIcon,
  Backpack: BackpackIcon,
  Luggage: LuggageIcon,
  Dice: DiceIcon,
  Hourglass: HourglassIcon,
  Lamp: LampIcon,
  Lantern: LanternIcon,
  Balloon: BalloonIcon,
  GameController: GameControllerIcon,
  MessageCircle: MessageCircleIcon,
  Chat: ChatIcon,
  Comment: CommentIcon,
  Megaphone: MegaphoneIcon,
  Bell: BellIcon,
  BellRing: BellRingIcon,
  Notification: NotificationIcon,
  Flag: FlagIcon,
  FlagTriangleRight: FlagTriangleRightIcon,
  Bookmark: BookmarkIcon,
  Heart: HeartIcon,
  Crown: CrownIcon,
  Medal: MedalIcon,
  Award: AwardIcon,
  Trophy: TrophyIcon,
  Diamond: DiamondIcon,
  Gem: GemIcon,
  Sparkle: SparkleIcon,
  Focus: FocusIcon,
  Goal: GoalIcon,
};

registerExtendedIcons(EXTENDED_ICON_MAP);
